projects/observability/src/shared/dashboard/data/graphql/explore/explore-result.test.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-result.ts

Made the access modifier as public, so that the "Others" name is accessible publically, to perform a conditional sorting on series based on name

chore: changed display text to others for explore

---

src/app/home/home.dashboard.ts

Update metric widgets on home dash.
1. Change order of errors/second & calls/second widgets.
2. Add average latency and p99 latency widgets.

feat: update metric widgets on home dash

---

projects/observability/src/shared/components/gauge-list/gauge-list.component.scss

The rows in the gauge list were getting squeezed if the rows lie outside the parent container. Scrolling the gauge list displays squeezed rows
Before
After

fix(gauge-list): rows outside container getting squeezed

---

projects/components/src/multi-select/multi-select.component.test.ts
projects/components/src/multi-select/multi-select.component.ts

Adding a triggerLabelDisplayMode input to multi-select that controls the behaviour of triggerLabel.
If its set to 'Placeholder', the label will always be the placeholder. If not, it'll show the selection summary as label.

fix: displayMode to control triggerLabel behaviour in multi-select

---

projects/components/src/table/data/table-cdk-data-source.ts
projects/components/src/table/table.component.scss
projects/components/src/table/table.component.ts
projects/observability/src/pages/explorer/explorer.component.scss

- Load Async is built to show loaders for content rendered inside it.
We are using it in table as a placeholder where the loader wrapper
stays after the cdk table has loaded all data. This creates lots of
layout issues especially when using with flex container
- Introducing a new hide property in table loading state to remove the
loader wrapper once loading is completed. In case of error or no data,
the loader will automatically take the entire space.
- removing host properties as it interferes with flex properties for parent container
- adding flex grow to explorer table

fix: fix table scrolling and loading issues

---

projects/components/src/public-api.ts
projects/components/src/toggle-button-group/button/toggle-button.component.scss
projects/components/src/toggle-button-group/toggle-button-group.component.ts

Take justifyContent property as an input to toggle button group.
Minor CSS updates.
Manual verification.

fix: toggle button group updates

---

projects/observability/src/shared/components/timeline-card-list/timeline-card-list.component.scss
projects/observability/src/shared/components/timeline-card-list/timeline-card-list.component.test.ts
projects/observability/src/shared/components/timeline-card-list/timeline-card-list.component.ts

refactor: adding borders to timeline card

refactor: adding borders to timeline card

---

projects/components/src/layout/layout-change-trigger.directive.ts

This change to layout triggering means a layout will be triggered on an initial render, in addition to the existing behavior of trigger on a render change. This is important as many visualizations depend on measuring their container to layout, which can't be accurately done until the parent has layed out.
Manually verified that the layout sequence produces an accurate measurement. This isn't feasible to automate, as our tests don't run with a layed out dom.
- [n/a] I have added tests that prove my fix is effective or that my feature works

fix: update layout trigger to emit on first layout

---

projects/components/src/modal/modal-container.component.scss

Fixing CSS for medium size modal

fix: fix css for medium modal dimensions

---

projects/distributed-tracing/src/public-api.ts
projects/observability/src/shared/components/gauge/gauge.component.ts
projects/observability/src/shared/dashboard/widgets/gauge/gauge-widget.model.test.ts
projects/observability/src/shared/dashboard/widgets/gauge/gauge-widget.model.ts
projects/observability/src/shared/dashboard/widgets/gauge/thresholds/gauge-threshold.model.ts

- Updating Gauge model to take max value and thresholds as model input
- Updating radius calculation for gauge. 
- Exporting an interaction handler service

refactor: updating gauge model, radius calculation and exporting handler service

---

projects/observability/src/shared/dashboard/widgets/gauge/gauge-widget.module.ts

refactor: load gauge threshold model

---

projects/components/src/table/table.component.test.ts
projects/components/src/table/table.component.ts

Tables within a modal/sheet were using the wrong x offsets to calculate their drag offsets. Fixed by using getBoundingClientRect() to get true offsets within the viewport rather than based on the DOM hierarchy.
Manually dragged columns of tables in various locations in the product.
[ X] My changes generate no new warnings
[ ] I have added tests that prove my fix is effective or that my feature works
[ X] Any dependent changes have been merged and published in downstream modules

fix: column resize inside sheet

---

projects/components/src/table/table.component.ts

Edit Columns option on the table used to show the entire set of columns, instead of just the visible columns. Fixed it to use the visible columns config
Verified manually by deploying UI locally

fix(table): show visible columns for edit columns option

---

projects/components/src/table/cells/expanded-detail/table-expanded-detail-row-cell-renderer.component.ts
projects/components/src/table/table.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

The change to use columnConfig$ as an Observable in table widget renderer caused this. The async pipe passed to columnConfig input on table was causing change detection. Fixed by comparing the values of the array instead of the array reference itself to determine if columnConfigs changed and we should initalizeColumns()
Tested against each of the table modes

Fix expandable rows resetting columns

---

projects/dashboards/src/test/dashboard-verification.ts

Table widget depends on getAttributeKeyDisplayName. When testing for a dashboard page with table, lots of errors are thrown on the table since the dashboardProviders bring a mock version of meta data service which has not implmentation for getAttributeKeyDisplayName. Due to this, the table fails at test run time, leading to errors and test failures

fix: adding mock value for getAttributeKeyDisplayName

---

projects/distributed-tracing/src/shared/dashboard/data/graphql/table/spans/spans-table-data-source.model.ts
projects/distributed-tracing/src/shared/dashboard/data/graphql/table/traces/traces-table-data-source.model.ts
projects/distributed-tracing/src/shared/dashboard/data/graphql/trace/traces-data-source.model.ts
projects/observability/src/pages/explorer/explorer.component.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts
projects/observability/src/shared/dashboard/data/graphql/table/entity/entity-table-data-source.model.ts

Reduce the amount of data fetched. It's rare to page beyond the second page, so we can load it as needed.
Updated unit tests to reflect new limits, verified UI locally

fix: reduce default fetch limits for faster loads

---

projects/components/src/table/table.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/waterfall-chart.component.scss

Closes: #411
Updates the waterfall to correctly synchronize table scrolling after table styling changed. Also fixed another bug around indented columns overlapping later columns
Verified waterfall and a few other table screens.

fix: synchronize waterfall scrolling

---

projects/components/src/combo-box/combo-box.component.ts

This fixes the input width for filterbox setting itself to a pixel value instead of 100% to now include when the text is an empty string. Previously we were only checking for undefined. This was causing issues if a user would clear out a filter and then try to repopulate it using the dropdown, but then switch to manual entry instead.

fix: filter box input should be full width when no text

---

projects/components/src/table/controls/table-controls.component.ts
projects/components/src/table/data/table-cdk-data-source.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.scss
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/observability/src/pages/explorer/explorer.component.scss

This fixes a few different table layout bugs:
- Empty table controls are still using up space due to padding
- Error state doesn't clear previous data
- In full screen mode (entity lists), the last row of data is hidden underneath the footer
- In embedded mode (explorer), the pagination controls are clipped
Beyond the unit tests, I visually verified the full and embedded table modes in error, no data and normal states.

fix: a number of table layout bugs

---

projects/distributed-tracing/src/public-api.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/data/api-trace-detail-data-source.model.test.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/data/api-trace-detail-data-source.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/data/trace-detail-data-source.model.test.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/data/trace-detail-data-source.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/trace-detail-widget-renderer.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/trace-detail-widget.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/trace-detail-widget.module.ts

Separate Trace and API Trace detail data sources so that Trace data source can be extended for other trace types.

feat: divide trace data source into trace and api trace

---

projects/components/src/table/header/table-header-cell-renderer.component.test.ts
projects/components/src/table/header/table-header-cell-renderer.component.ts

Show sort related options in hover options menu only if sortable is true for the column.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally.

feat: hide sort options in hover menu options if sortable is false

---

.circleci/config.yml

While updating release workflow to `release-publish` and `merge-publish` in https://github.com/hypertrace/hypertrace-ui/pull/383 we missed adding this require step in `release-publish` which is blocking release of artifacts. 
NA
- [NA] I have added tests that prove my fix is effective or that my feature works

fixes release workflow

---

.circleci/config.yml

Circleci is building based release tags. According to circleci documentation, we need to add tag based filter on the jobs on which workflow jobs are dependent.
https://circleci.com/docs/2.0/configuration-reference/#tags

Add tag based filter to circleci jobs

---

projects/observability/src/shared/components/label-detail/label-detail.component.scss
projects/observability/src/shared/components/label-detail/label-detail.component.test.ts
projects/observability/src/shared/components/label-detail/label-detail.component.ts
projects/observability/src/shared/components/label-detail/label-detail.module.ts

feat: adding icon only view mode

---

projects/components/src/table/data/table-cdk-data-source.ts

- When we first rebuild the table data source, we need to emit 'Never' on
the loading subject. This would allow the table to show loader icon
when a new data source is built due to the addition of a new
table filter.

fix: table loader should start with Never

---

projects/observability/src/pages/apis/api-detail/api-detail-breadcrumb.resolver.test.ts
projects/observability/src/pages/apis/api-detail/api-detail-breadcrumb.resolver.ts
projects/observability/src/pages/apis/service-detail/service-detail-breadcrumb.resolver.test.ts
projects/observability/src/pages/apis/service-detail/service-detail-breadcrumb.resolver.ts

Avoid caching for entity requests for breadcrumbs
UTs added

fix: avoid caching for entity requests for breadcrumbs

---

.github/workflows/build-and-test.yml
package.json

ci: optimize ci speed

---

projects/components/src/table/table.component.scss
projects/components/src/titled-content/titled-content.component.scss
src/app/application-frame/application-frame.component.scss

Topology, donut, radar, and table were not showing in Safari due to Safari not handling flexbox the same as other browsers.

fix table app frame and title content scss to work with safari

---

projects/components/src/paginator/paginator.component.scss
projects/components/src/panel/panel.component.scss
projects/components/src/table/table.component.scss
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.scss
projects/observability/src/pages/explorer/explorer.component.scss
projects/observability/src/pages/explorer/explorer.component.ts

After fixing the Safari issues with flexbox, the Explorer table was expanding beyond the page limits. This PR fixes that and a few other small styling issues with table in explorer.
Manual testing of this table and tables in other parts of the product, including entity lists, events, and api def.

fix: explorer table expanding beyond page bounds

---

projects/components/src/overlay/sheet/sheet-overlay.component.test.ts
projects/components/src/overlay/sheet/sheet-overlay.component.ts
projects/distributed-tracing/src/shared/dashboard/interaction/detail-sheet/container/detail-sheet-interaction-container.component.ts
projects/distributed-tracing/src/shared/dashboard/interaction/detail-sheet/detail-sheet-interaction-handler.service.test.ts
projects/distributed-tracing/src/shared/dashboard/interaction/detail-sheet/detail-sheet-interaction-handler.service.ts

Fixes an issue from #493 where the new isolated injector is not exposing the layout service.
Verified UI, updated unit tests

fix: fix sheet injection to include layout

---

projects/components/src/menu-dropdown/menu-item/menu-item.component.scss
projects/components/src/menu-dropdown/menu-item/menu-item.component.test.ts
projects/components/src/menu-dropdown/menu-item/menu-item.component.ts

Support for disabling a menu item.
Manually tested. UT added.

feat: support for disabling a menu item

---

projects/common/src/color/color.ts
projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.test.ts
projects/components/src/multi-select/multi-select.component.ts
projects/components/src/multi-select/multi-select.module.ts

feat: adding "all" option and fixing some styling

feat: adding all option and fixing some styling

---

projects/components/src/search-box/search-box.component.test.ts
projects/components/src/search-box/search-box.component.ts

fix: adding debounce subscription on component init

fix: adding debounce subscription on component init

---

projects/components/src/search-box/search-box.component.scss
projects/observability/src/pages/apis/endpoints/endpoint-list.component.ts
projects/observability/src/pages/apis/endpoints/endpoint-list.dashboard.ts
projects/observability/src/pages/apis/endpoints/endpoint-list.module.ts
projects/observability/src/pages/apis/services/service-list.dashboard.ts
projects/observability/src/public-api.ts
src/app/entity-metadata.ts
src/app/routes/endpoints/endpoint-routing.module.ts
src/app/routes/root-routing.module.ts
src/app/shared/navigation/navigation.component.ts
src/environments/environment.ts

Restore flat service list (not the tree variant) in addition to the new flat endpoint list.
Ran unit tests, verified UI locally

fix: restore service list as flat list

---

projects/components/src/multi-select/multi-select.component.ts

refactor: setting min dropdown width to be equal to trigger width

refactor: setting min dropdown width to be equal to trigger width

---

projects/assets-library/assets/styles/_interaction.scss
projects/components/src/header/application/application-header.component.scss
projects/components/src/header/application/application-header.component.ts
projects/components/src/select/select.component.scss
projects/components/src/select/select.component.ts
projects/components/src/time-range/time-range.component.scss

This rearranged some styles used by components in the app header so they can come from a single source of truth, rather than being redeclared in each component. The select component was also updated to actually respond to its size argument, which was previously ignored.
Visual verification on top of unit tests.

refactor: rearrange styles for sharing in app header

---

src/app/shared/navigation/navigation.component.scss

Remove padding from parent nav since it was added to the component in https://github.com/hypertrace/hypertrace-ui/pull/530
Visual verification

fix: remove duplicate padding

---

projects/components/src/select/select-size.ts
projects/components/src/select/select.component.scss

Add large size support for select component
N/A

fix: add large size for Select component

---

projects/components/src/overlay/overlay.service.test.ts
projects/components/src/overlay/overlay.service.ts
projects/components/src/overlay/sheet/default-sheet-ref.ts
projects/components/src/overlay/sheet/sheet.ts
projects/distributed-tracing/src/shared/dashboard/interaction/detail-sheet/detail-sheet-interaction-handler.model.ts
projects/distributed-tracing/src/shared/dashboard/interaction/detail-sheet/detail-sheet-interaction-handler.service.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall-widget-renderer.component.ts

feat: adding sheet ref

---

projects/common/src/navigation/navigation.service.test.ts
projects/common/src/navigation/navigation.service.ts
projects/common/src/time/time-range.service.ts

This change removes the knowledge of other services from navigation service, allowing them to register global query params (rather than hardcoding them) for a more decoupled design.
Updated and added new unit tests

refactor: move knowledge of global params out of nav service

---

projects/components/src/time-range/time-range.component.scss
projects/components/src/time-range/time-range.component.ts

Unifying the top nav color through style overrides overrode the emphasized style for the refresh button, which we want to keep. This changes the override to only apply when the refresh button is not meant to be emphasized.
Visual verification

fix: leave time range refresh button blue in primary mode

---

projects/common/src/time/time-duration.test.ts
projects/common/src/time/time-duration.ts

Method to convert duration to ISO8601 duration string.
UT added.

feat: method to convert duration to ISO8601 duration string

---

package-lock.json
package.json
projects/common/package.json
projects/common/src/time/time-duration.test.ts
projects/common/src/time/time-duration.ts

Support for parsing ISO 8601 duration string
UT added.

feat: support to parse ISO 8601 duration string

---

projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-view-toggle.model.ts

Fixes issue with initial checkbox filter not being applied to query due to table being wrapped in TableWidgetViewToggleModel. This is due to the the TableWidgetViewToggleModel requiring a view be set prior to it creating the delegate model.

fix: initial checkbox filtering when using view toggle model

---

projects/distributed-tracing/src/public-api.ts
projects/distributed-tracing/src/shared/graphql/model/schema/filter/global-graphql-filter.service.test.ts
projects/distributed-tracing/src/shared/graphql/model/schema/filter/global-graphql-filter.service.ts
projects/distributed-tracing/src/shared/graphql/request/handlers/spans/spans-graphql-query-handler.service.ts
projects/distributed-tracing/src/shared/graphql/request/handlers/traces/trace-graphql-query-handler.service.ts
projects/distributed-tracing/src/shared/graphql/request/handlers/traces/traces-graphql-query-handler.service.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-builder.service.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.test.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.ts

This change adds support for registering global filter rules which will be applied to all graphql handlers. This allows rules to be managed independently of the various handlers, a more extensible design.
Added and updated unit tests

feat: add global filtering that applies aross all queries

---

projects/observability/src/shared/graphql/request/builders/argument/graphql-observability-argument-builder.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-builder.service.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-handler.service.test.ts

support for includeInactive param in entities gql request
Manually tested. UTs added.

feat: support for includeInactive param in entities gql request

---

projects/observability/src/pages/api-trace-detail/api-trace-detail.page.component.ts

Using start time while navigating to full trace page.
N/A

fix: using startTime for full trace page

---

projects/components/src/viewer/json-viewer/json-viewer.component.scss

Fix to prevent long json viewer strings from causing overflow.

fix: break-all for json-viewer strings

---

projects/components/src/overlay/sheet/sheet-overlay.component.ts
projects/components/src/select/select.component.scss
projects/components/src/select/select.component.test.ts
projects/components/src/select/select.component.ts
projects/components/src/select/select.module.ts

Icon only mode for select trigger
UTs added. Manually tested.

feat: icon only mode for select trigger

---

projects/components/src/select/select-option.component.ts
projects/components/src/select/select-option.ts
projects/components/src/select/select.component.test.ts
projects/components/src/select/select.component.ts

Add support for a separate `selectedLabel` for select options in select component.
In some cases we'd want to show a different label when the action is selected. For example, when the option is an action like 'Resolve', we'd want to show 'Resolved' when that option is selected.
UTs added.

feat(select): add support for a separate selected label

---

projects/components/src/breadcrumbs/breadcrumbs.component.scss

- Remove bottom padding which change component position in global layout.
As this padding don't affect position of elements inside component we can add padding to parent component

fix(breadcrumbs): remove  bottom padding

---

projects/observability/src/public-api.ts
projects/observability/src/shared/components/topology/d3/d3-topology.ts
projects/observability/src/shared/components/topology/d3/interactions/zoom/topology-zoom.ts
projects/observability/src/shared/components/utils/d3/zoom/d3-zoom.ts

feat: separate zoom into a shared util file

feat: separate zoom into a shared util file

---

projects/components/src/table/cells/data-renderers/code/code-table-cell-renderer.component.scss
projects/components/src/table/cells/data-renderers/code/code-table-cell-renderer.component.test.ts
projects/components/src/table/cells/data-renderers/code/code-table-cell-renderer.component.ts
projects/components/src/table/cells/table-cells.module.ts
projects/components/src/table/cells/types/core-table-cell-renderer-type.ts

Adds a code-style table cell renderer that uses a gray background and monospaced font.
Added unit tests, verified in action. Also checked case of no data and data too long to fit to verify that they show "Unknown" and truncate, respectively.

feat: add code table cell renderer

---

projects/components/src/table/data/table-cdk-data-source.ts

The table was making more and more requests over time as inputs changed. Issue was we recreate data sources frequently, but there was a subscription inside the data source not being cleaned up on disconnect. 
Manual verification + running existing tests

fix: make table remove subscription on disconnect

---

projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-control.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/observability/src/shared/dashboard/data/graphql/entity/attribute/entities-attribute-options-data-source.model.ts

Add `visible` property to table widget controls to allow them to be toggled off.

feat: add visible option to table controls

---

projects/common/src/navigation/breadcrumb.ts
projects/components/src/breadcrumbs/breadcrumbs.component.test.ts
projects/components/src/breadcrumbs/breadcrumbs.component.ts
projects/components/src/header/page/page-header.component.ts
projects/observability/src/pages/apis/backend-detail/backend-detail-breadcrumb.resolver.test.ts
projects/observability/src/pages/apis/backend-detail/backend-detail-breadcrumb.resolver.ts

This PR removes the double icons present in the breadcrumbs and the header, particularly in ht-page-header also to show or not the icons in the crumbs following the first crumb.
Visual verification

fix: remove primary icon

---

projects/components/src/modal/modal-container.component.scss
projects/components/src/modal/modal.ts
projects/components/src/textarea/textarea.component.scss
projects/components/src/textarea/textarea.component.ts

* Update styling for textarea (first usage)
* Add taller large modal size

Modal and textarea styling

---

projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.scss
projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.test.ts
projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.ts
projects/components/src/table/cells/table-cells.module.ts
projects/components/src/table/cells/types/core-table-cell-renderer-type.ts

Cell renderer for string arrays.
Expected behaviour:
Should show the first item in the cell, along with a `+x` representing the number of remaining values. Tooltip should show a list of these values on hovering on `+x`.
Overflow
Manually verified. Added UTs.

feat: string array cell renderer

---

projects/common/src/public-api.ts
projects/common/src/utilities/formatters/string/string-formatter.test.ts
projects/common/src/utilities/formatters/string/string-formatter.ts
projects/common/src/utilities/validators/email-validator.test.ts
projects/common/src/utilities/validators/email-validator.ts

Validator for email.
String formatter to split a comma separated list into a string array.
UTs added.

feat: email validator and a string formatter

---

projects/components/src/toggle-switch/toggle-switch-size.ts
projects/components/src/toggle-switch/toggle-switch.component.scss
projects/components/src/toggle-switch/toggle-switch.component.test.ts
projects/components/src/toggle-switch/toggle-switch.component.ts
projects/components/src/toggle-switch/toggle-switch.module.ts

Added an optional input to modify the default styles of the toggle switch that were defined as small. The styles were encapsulated in relation to the new class.
Visual Verification.

feat: adding size option to toggle switch components

---

projects/components/src/table/cells/data-renderers/text-with-copy/text-with-copy-table-cell-renderer.component.scss
projects/components/src/table/cells/data-renderers/text-with-copy/text-with-copy-table-cell-renderer.component.test.ts
projects/components/src/table/cells/data-renderers/text-with-copy/text-with-copy-table-cell-renderer.component.ts
projects/components/src/table/cells/table-cells.module.ts
projects/components/src/table/cells/types/core-table-cell-renderer-type.ts

Cell renderer to display text with a copy action on hover.
Tested manually. UT added.
https://user-images.githubusercontent.com/63222211/110629511-3c4d2e00-81ca-11eb-8ad5-d0814a3b99d4.mov

feat: cell renderer for text with copy action

---

projects/components/src/toggle-group/toggle-group.component.test.ts
projects/components/src/toggle-group/toggle-group.component.ts
projects/components/src/toggle-group/toggle-group.module.ts
projects/components/src/toggle-group/toggle-item.component.scss
projects/components/src/toggle-group/toggle-item.component.ts
projects/components/src/toggle-group/toggle-item.ts

Icon support was added for toggle groups, keeping support for labels.
Visual Testing 

feat: adding icon support to toggle group

---

projects/assets-library/assets/styles/_color-palette.scss
projects/components/src/modal/modal-container.component.scss
projects/components/src/modal/modal.ts

New modal size for LargeShort.

feat: add large short modal size and fix cloud colors

---

projects/components/src/select/select.component.scss

Remove host max width for select component.
Containers of the component should be able to control the width.

fix: remove host max width for select component

---

.github/workflows/build-and-test.yml

Dependabot now has a read only token and fails to upload test results - so making that optional.

ci: ignore error in unit test result publish

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
projects/observability/src/pages/explorer/explorer.component.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.ts
projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts
projects/observability/src/shared/components/explore-query-editor/limit/explore-query-limit-editor.component.scss
projects/observability/src/shared/components/explore-query-editor/limit/explore-query-limit-editor.component.test.ts
projects/observability/src/shared/components/explore-query-editor/limit/explore-query-limit-editor.component.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/table/explore/explore-table-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/trace/donut/trace-donut-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/trace/donut/trace-donut-data-source.model.ts
projects/observability/src/shared/dashboard/widgets/top-n/data/top-n-data-source.model.ts
projects/observability/src/shared/graphql/model/schema/groupby/graphql-group-by.ts
projects/observability/src/shared/graphql/request/builders/argument/graphql-observability-argument-builder.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.test.ts

Uses the new group limit parameter in explorer api instead of the deprecated row limit behavior.
Visual verification, updated tests

refactor: use new group limit in explorer

---

projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.ts

Multi select options should overflow.
Manually verified.

fix: allow multi select options to overflow

---

projects/components/src/table/header/table-header-cell-renderer.component.scss

A column is darkened/highlighted when sorting is active for that header.
Visual Test

fix: header title highlighted when sorting

---

projects/components/src/summary-list/summary-list-api.ts
projects/components/src/summary-list/summary-list.component.scss
projects/components/src/summary-list/summary-list.component.test.ts
projects/components/src/summary-list/summary-list.component.ts
projects/components/src/table/controls/table-controls.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-base.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-view-toggle.model.ts

Added styling and @Output for summary list values that are clickable.
Also added configurable searchPlaceholder to table controls.

Summary list clickable

---

projects/dashboards/src/widgets/header/widget-header.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-base.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.scss
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/observability/src/pages/apis/backend-detail/overview/backend-overview.component.ts

Add spacing between title and table content if a title is provided.

feat: add spacing between title and table when title is set

---

projects/observability/src/shared/graphql/request/handlers/entities/query/entity/entity-graphql-query-handler.service.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/interactions/interactions-graphql-query-handler.service.ts

All single entity queries by ID will set `includeInactive` to true.

feat: request includeInactive for all entity id queries

---

projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.test.ts
projects/components/src/multi-select/multi-select.component.ts
projects/components/src/multi-select/multi-select.module.ts

The checkbox used within the multi-select component was replaced by the component belonging to the library and also some minor styles were modified.
- Visual test

fix: updating checkbox component in multi-select

---

projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/data/api-trace-detail-data-source.model.test.ts
projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/data/api-trace-detail-data-source.model.ts

apiCalleeNameCount is a valid attribute only for trace type 'API_TRACE'. This PR updates api trace detail data source to request for apiCalleeNameCount attribute only for API_TRACE type requests.
Tested manually. UT added.

fix: request apiCalleeNameCount only for API_TRACE

---

projects/observability/src/shared/components/topology/d3/d3-topology.ts
projects/observability/src/shared/components/topology/renderers/tooltip/topology-tooltip-popover.ts
projects/observability/src/shared/components/topology/topology.ts

The popover is positioned near the node or edge where the user hovers or clicks, dynamically adjusting to the screen.
Visual Testing 
Hovering:
After click:

fix: Unable to click topology

---

projects/common/src/utilities/formatters/string/string-formatter.test.ts
projects/common/src/utilities/formatters/string/string-formatter.ts

refactor: updating display string to show 'null' as '-'

refactor: updating display string to show 'null' as '-'

---

projects/components/src/beta-tag/beta-tag.component.ts
projects/components/src/beta-tag/beta-tag.module.ts
projects/components/src/navigation/nav-item/nav-item.component.scss
projects/components/src/navigation/nav-item/nav-item.component.ts
projects/components/src/navigation/navigation-list.component.scss
projects/components/src/navigation/navigation-list.component.ts

Support displaying beta tag on left nav items.
Manually verified

feat: support displaying beta tag in left nav item

---

projects/components/src/table/cells/data-renderers/table-data-cell-renderer.component.scss
projects/components/src/table/table.component.scss

Column bars padding was removed and content was centered.
Visual Testing
Before: 
After: 

fix: table column and content misalignment

---

projects/components/src/button/button.component.test.ts
projects/components/src/button/button.component.ts
projects/components/src/time-range/time-range.component.ts

Adding Medium Size Icon Support in button (24px x 24px) also I modified the time-range component using Medium size Icons. 
Visual Testing.

feat: adding Medium size icon support in button

---

projects/common/src/public-api.ts
projects/common/src/utilities/formatters/enum/display-string-enum.pipe.ts
projects/common/src/utilities/formatters/enum/display-string-enum.test.ts
projects/common/src/utilities/formatters/enum/display-string-enum.ts
projects/common/src/utilities/formatters/formatting.module.ts

We keep using the same code over and over. Turning it into a const method and pipe.

Display string enum pipe

---

projects/components/src/tabs/navigable/navigable-tab-group.component.scss

Reducing space in Tab's titles.
Visual Testing
Before:
After:

fix: reducing space in tab's title

---

projects/components/src/menu-dropdown/menu-item/menu-item.component.test.ts
projects/components/src/menu-dropdown/menu-item/menu-item.component.ts

The color parameter is added to be able to use customs colors in the label of the menu item.
Visual testing.

feat: adding parameter for color to menu item

---

projects/common/src/utilities/coercers/date-coercer.test.ts
projects/dashboards/src/model/time-duration/time-duration.model.ts
projects/observability/src/shared/components/interval-select/interval-select.component.ts
projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget-renderer.component.test.ts
projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget-renderer.component.ts
projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget.model.ts

feat: adding default interval for cartesian

feat: adding default interval for cartesian

---

projects/components/src/time-range/time-range.component.scss

The button corresponding to the time is changed from 32px to 36px in height.
Visual Testing

fix: enlarging button height

---

projects/observability/src/public-api.ts
projects/observability/src/shared/components/explore-filter-link/explore-filter-link.component.scss
projects/observability/src/shared/components/explore-filter-link/explore-filter-link.component.test.ts
projects/observability/src/shared/components/explore-filter-link/explore-filter-link.component.ts
projects/observability/src/shared/components/explore-filter-link/explore-filter-link.module.ts

feat: adding explore filter link component

feat: adding explore filter link component

---

projects/components/src/paginator/paginator.component.test.ts
projects/components/src/paginator/paginator.component.ts

Turn on paginator when total items are greater than the smallest item in the page size drop-down menu.
Visual testing

feat: turn on paginator when total Items are larger than page size

---

projects/components/src/textarea/textarea.component.scss
projects/components/src/textarea/textarea.component.test.ts
projects/components/src/textarea/textarea.component.ts
projects/components/src/textarea/textarea.module.ts

- Adding rows count feature to Textarea component. 
- Adding minHeight feature to Textarea component. 
Visual Testing
Old:
New:

feat: adding rows count to textarea

---

projects/components/src/table/table.component.scss

The paginator was updated to hide if not needed, which makes the positioning of the state watcher extra weird. Previously, it was centering between the top of the header row and the top of the paginator. Now that the paginator is hidden in loading and error scenarios (when there's no data to power the paginator), this skews quite high in the component (more extreme for smaller tables). With this change, it centers in the whitespace underneath the header.
After change:
Before:
Visual (on a main list and embedded)

refactor: update positioning of table state watcher

---

projects/components/src/table/cells/data-renderers/enum/string-enum-table-cell-renderer.component.scss
projects/components/src/table/cells/data-renderers/enum/string-enum-table-cell-renderer.component.test.ts
projects/components/src/table/cells/data-renderers/enum/string-enum-table-cell-renderer.component.ts
projects/components/src/table/cells/table-cells.module.ts
projects/components/src/table/cells/types/core-table-cell-renderer-type.ts
src/styles/main.scss

Added table cell renderer to format string enums into more human readable text.

feat: string enum table cell renderer

---

projects/observability/src/pages/apis/api-detail/traces/api-trace-list.dashboard.ts
projects/observability/src/pages/apis/service-detail/traces/service-trace-list.dashboard.ts
projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
projects/observability/src/pages/explorer/explorer-dashboard-builder.ts

Adding error column in trace table

feat: adding error column in trace table

---

projects/distributed-tracing/src/public-api.ts
projects/observability/src/shared/graphql/request/builders/specification/explore/explore-specification-builder.ts

refactor: only add aggregation in fragment if value is present

refactor: only add aggregation in fragment if value is present

---

projects/components/src/paginator/paginator.component.ts
projects/components/src/table/table.component.ts

Tables should switch page to page one if the user searches, applies a sort or filters. Currently, any offset is preserved meaning a search when on page two will show you page two of search results etc. The cause of this is three parts - 
1. the paginator, which actually pushes changes to the data, only pushed if the change was caused by the component itself, not if the inputs to the paginator changed.
2. The table only pushed changes to the paginator when the url/route changed
3. Because changes emitting from the paginator never made it back to the paginator's inputs, change detection in the reset case wasn't firing (because the reset page was equivalent to the last page input)
Visual/E2E

fix: reset paging if table filters or sorts

---

projects/components/src/table/cells/data-renderers/enum/string-enum-table-cell-renderer.component.ts
projects/components/src/table/columns/table-edit-columns-modal.component.ts

This fixes an issue where meta type columns were showing up in the table's add/remove column modal. We've expanded the types of meta columns beyond just `$$state` and this change augments the filter used to remove these types of columns from the list.

fix: filter out all meta types from table edit columns modal

---

projects/components/src/sequence/sequence-chart.component.ts
projects/components/src/sequence/sequence.ts
projects/distributed-tracing/src/pages/trace-detail/trace-detail.service.ts
projects/distributed-tracing/src/shared/components/span-detail/span-title.ts
projects/distributed-tracing/src/shared/dashboard/data/graphql/waterfall/trace-waterfall-data-source.model.test.ts
projects/distributed-tracing/src/shared/dashboard/data/graphql/waterfall/trace-waterfall-data-source.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/span-name/span-name-cell-data.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/span-name/span-name-table-cell-parser.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/span-name/span-name-table-cell-renderer.component.test.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/span-name/span-name-table-cell-renderer.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/waterfall-chart.component.test.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/waterfall-chart.module.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/waterfall-chart.service.ts
projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/waterfall-chart.ts
projects/observability/src/shared/dashboard/data/graphql/waterfall/api-trace-waterfall-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/waterfall/api-trace-waterfall-data-source.model.ts

This fixes undefined strings in several places for waterfall.

fix: waterfall undefined strings

---

projects/components/src/table/columns/table-edit-columns-modal.component.ts
projects/components/src/table/header/table-header-cell-renderer.component.test.ts
projects/components/src/table/header/table-header-cell-renderer.component.ts

This fixes some usability issues around the table column options button showing and also what we show for edit columns.
Before the button always showed, even when there were no options or when none of the columns are editable. The button will now hide if there is no benefit to the user by providing it, as in the above two examples.

Fix table editable columns option

---

projects/observability/src/pages/apis/api-detail/overview/api-overview.dashboard.ts
projects/observability/src/pages/apis/backend-detail/overview/backend-overview.component.ts
projects/observability/src/pages/apis/service-detail/overview/service-overview.dashboard.ts
src/app/home/home.dashboard.ts

Resolves https://github.com/hypertrace/hypertrace-ui/issues/749 by making changes as per the discussion here: https://github.com/hypertrace/hypertrace-ui/issues/749#issuecomment-829140138 . 
Enabling `selectable-interval` will show up in UI like this screenshot from earlier version:
NA

fix: enable selectable time intervals for metrics across all screens

---

projects/components/src/table/table.component.scss
projects/components/src/table/table.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-base.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

Non resizable columns functionality in table

feat: non resizable columns functionality in table

---

projects/components/src/popover/popover.component.ts

Today, when moving away from a view with a popup (for example, a modal) any open popovers remain hanging open. This change ties their lifecycle to the underlying component, so the popover overlay will be removed if the trigger itself is destroyed.
Tested manually

fix: close popup on destroy

---

projects/observability/src/shared/components/entity-renderer/entity-renderer.component.test.ts
projects/observability/src/shared/components/entity-renderer/entity-renderer.component.ts
projects/observability/src/shared/components/table/data-cell/entity/entity-table-cell-parser.ts
projects/observability/src/shared/components/table/data-cell/entity/entity-table-cell-renderer-util.ts
projects/observability/src/shared/components/table/data-cell/entity/entity-table-cell-renderer.component.test.ts
projects/observability/src/shared/components/table/data-cell/entity/entity-table-cell-renderer.component.ts
projects/observability/src/shared/constants/entity-metadata.ts
projects/observability/src/shared/services/navigation/entity/entity-navigation.service.ts

This change allows navigation routes to know when an entity is inactive so it can be routed differently if needed.

feat: add navigation handling for inactive entities

---

projects/observability/src/shared/components/entity-renderer/entity-renderer.component.scss
projects/observability/src/shared/components/entity-renderer/entity-renderer.component.test.ts
projects/observability/src/shared/components/entity-renderer/entity-renderer.component.ts

feat: adding inherit color from text input to entity

feat: adding inherit color from text input to entity

---

projects/common/src/utilities/lang/lang-utils.ts
projects/components/src/popover/popover.component.ts
projects/components/src/table/controls/table-controls-api.ts
projects/components/src/table/controls/table-controls.component.test.ts
projects/components/src/table/controls/table-controls.component.ts
projects/distributed-tracing/src/shared/dashboard/data/graphql/graphql-table-control-options-data-source.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-control-checkbox-option.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-control-select-option.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-control.model.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/observability/src/pages/apis/endpoints/endpoint-list.dashboard.ts
projects/observability/src/shared/dashboard/data/graphql/entity/attribute/entities-attribute-options-data-source.model.ts

This change is to make all of the table control dropdowns multiselect instead of single select. 
It also cleans up some messiness around the table control filter types. Using multi-select is actually easier to configure because it no-longer requires an `Unset` option in the dropdown. This simplifies the API for the `select` dropdowns and reduces its possible filter types to just `TableControlOptionType.Filter`. Now only `checkbox` table controls use `TableControlOptionType.Unset` and `TableControlOptionType.Property` types.
https://user-images.githubusercontent.com/45181984/117207822-4134f500-ada9-11eb-8ce1-0135296d830a.mov

Table multiselect filters

---

projects/components/src/table/data/table-data-source.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

Rather than requiring dummy implementations of getScope everywhere, this allows omitting it if not needed.

refactor: make table scope optional

---

projects/components/src/list-view/list-view.component.scss
projects/distributed-tracing/src/shared/components/log-events/log-events-table.component.scss

fix: style fixes

---

projects/common/src/public-api.ts
projects/common/src/utilities/dom/dom-element-scroll-into-view.service.ts
projects/common/src/utilities/formatters/string/highlight.pipe.ts
projects/components/src/combo-box/combo-box-api.ts
projects/components/src/combo-box/combo-box.component.scss
projects/components/src/combo-box/combo-box.component.test.ts
projects/components/src/combo-box/combo-box.component.ts

This adds the ability to "Create new" value using combo-box autocomplete.

feat: update combo-box to account for 'create new' autocomplete use cases

---

projects/distributed-tracing/src/shared/components/log-events/log-events-table.component.ts
projects/distributed-tracing/src/shared/components/log-events/log-events-table.module.ts

Small fix to memoize call to `getLogEventAttributeRecords`. This stops it from calling multiple times and triggering change detection in `ht-list-view`.

feat: memoize record method call so it is only called once

---

projects/components/src/combo-box/combo-box.component.scss

Remove horizontal scrollbar from combo-box dropdown.

fix: combo-box dropdown overflow-x

---

projects/components/src/select/select.component.scss
projects/components/src/select/select.component.ts

Adding select new display view
Visual Testing
old:
new:

feat: adding select new display view

---

projects/components/src/table/cells/data-parsers/table-cell-no-op-parser.ts

Table Cell NoOp was updated to allow single data in the parser

feat: table cell no-op parser update

---

projects/components/src/select/select.component.test.ts
projects/components/src/select/select.component.ts
projects/components/src/select/select.module.ts

show selected item's icon in trigger label if applicable
Manually verified. UT added.

feat: show selected item's icon in trigger label if applicable

---

projects/components/src/navigation/nav-item/nav-item.component.test.ts
projects/components/src/navigation/nav-item/nav-item.component.ts
projects/components/src/navigation/navigation-list.component.test.ts
projects/components/src/navigation/navigation-list.component.ts
projects/components/src/navigation/navigation-list.module.ts
projects/components/src/tabs/navigable/navigable-tab-group.component.ts
projects/components/src/tabs/navigable/navigable-tab.module.ts

fix: adding hyperlink capabilities to nav items and nav tabs

fix: adding hyperlink capabilities to nav items and nav tabs

---

projects/components/src/link/link.component.ts

When used with async pipe, link would error on initial null state.

chore: allow ht link to support null from async pipe

---

projects/components/src/form-field/form-field.component.scss
projects/components/src/form-field/form-field.component.test.ts
projects/components/src/form-field/form-field.component.ts
projects/components/src/form-field/form-field.module.ts
projects/components/src/public-api.ts

A new component was created that works as a wrapper for the label, icon, and input field to have a standard to insert in the different components. The component allows attaching any input field present in the library
Unit test and visual test.
References:

feat: Adding form field wrapper

---

projects/common/src/color/color.ts

chore: new color

---

projects/components/src/radio/radio-group.component.scss
projects/components/src/radio/radio-group.component.ts

Radio buttons disabled new styles.
Visual Testing
Old:
New:

feat: Radio button disabled Styles

---

projects/components/src/confirmation/confirmation-modal.component.scss

word wrap update for confirmation modal content

fix: word wrap update for confirmation modal content

---

projects/components/src/form-field/form-field.component.scss
projects/components/src/form-field/form-field.component.ts

Form Field small fixes.
- Removing unused padding
- Removing empty div when it has no label.
File Inspection.

fix: form field small fix

---

projects/components/src/radio/radio-group.component.scss
projects/components/src/radio/radio-group.component.ts

Adding the attribute to configure horizontal/vertical options alignment from Radio Group (column default alignment).
Visual Testing
Row View:
Column View:

feat: adding options alignment in Radio Group

---

projects/components/src/table/controls/table-controls-api.ts
projects/components/src/table/controls/table-controls.component.ts
projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

This fixes a bug where when a table filter is applied and a user uses the internal refresh in the top bar, the table controls get cleared and there is no indication to the user that the filter is still applied. With this change, we now look at the currently applied filters and reapply them to the table controls upon refresh.

Fix to retain table control filters on refresh

---

projects/distributed-tracing/src/shared/dashboard/dashboard-wrapper/application-aware-dashboard.component.ts
projects/distributed-tracing/src/shared/dashboard/dashboard-wrapper/navigable-dashboard.component.ts

Pushing the ability to set variables down to app aware dashboard, since it has nothing to do with navigation.
Quick sanity test, but ust a refactor of an existing feature.

refactor: push variables down to app-aware-dash

---

projects/observability/src/shared/components/topology/d3/d3-topology.ts
projects/observability/src/shared/components/topology/d3/interactions/topology-interaction-control.component.ts
projects/observability/src/shared/components/topology/topology.component.ts
projects/observability/src/shared/components/topology/topology.ts
projects/observability/src/shared/dashboard/widgets/topology/topology-widget-renderer.component.test.ts
projects/observability/src/shared/dashboard/widgets/topology/topology-widget-renderer.component.ts
projects/observability/src/shared/dashboard/widgets/topology/topology-widget.model.ts

Add custom configurations to the topology widget
- Make legend optional
- Make minimap/brush optional
- Add zoom to fit configuration

feat: add custom configurations to the topology widget

---

projects/observability/src/shared/components/topology/d3/interactions/topology-interaction-control.component.scss
projects/observability/src/shared/components/topology/d3/interactions/topology-interaction-control.component.ts
projects/observability/src/shared/dashboard/widgets/topology/topology-widget-renderer.component.scss
projects/observability/src/shared/dashboard/widgets/topology/topology-widget-renderer.component.ts
projects/observability/src/shared/dashboard/widgets/topology/topology-widget.model.ts

- Small interaction buttons
- Adding new box style config

feat: custom style for topology

---

projects/common/src/navigation/navigation.service.ts

Link observable was only emitting after a change in route, so initial state was empty.
Manual

fix: build initiial nav params on observable

---

projects/components/src/button/button.component.scss
projects/components/src/button/button.component.test.ts
projects/components/src/button/button.component.ts
projects/components/src/button/button.ts

- Add a new style called 'Plain Text' similar to 'Text' but without padding. 
Visual testing. 
- 'Text' style with padding
- 'Plain Text' style with no padding

Adding new style button

---

projects/components/src/input/input.component.scss
projects/components/src/input/input.component.test.ts
projects/components/src/input/input.component.ts

Styling for disabled input.
Tested manually. UTs added.

feat: styling for disabled input

---

projects/common/src/feature/feature.guard.test.ts
projects/common/src/feature/feature.guard.ts
projects/common/src/navigation/ht-route-data.ts
projects/common/src/navigation/ht-route.ts
projects/common/src/navigation/navigation.service.ts
projects/common/src/navigation/trace-route.ts
projects/common/src/public-api.ts
projects/components/src/breadcrumbs/breadcrumbs.service.test.ts
projects/distributed-tracing/src/pages/spans/span-list.page.module.ts
projects/distributed-tracing/src/pages/trace-detail/trace-detail.page.module.ts
projects/observability/src/pages/api-trace-detail/api-trace-detail.page.module.ts
src/app/home/home.module.ts
src/app/routes/application-flow/application-flow-routing.module.ts
src/app/routes/backends/backend-detail/backend-detail-routing.module.ts
src/app/routes/backends/backends-routing.module.ts
src/app/routes/endpoints/endpoint-detail/endpoint-detail-routing.module.ts
src/app/routes/endpoints/endpoint-routing.module.ts
src/app/routes/explorer/explorer-routing.module.ts
src/app/routes/root-routing.module.ts
src/app/routes/services/service-detail/service-detail-routing.module.ts
src/app/routes/services/services-routing.module.ts
src/app/shared/navigation/navigation.component.ts

chore: rename route interface

---

projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.test.ts
projects/components/src/multi-select/multi-select.component.ts

support disabling options in multi-select
Manually verified. UTs added.
- [x I have added tests that prove my fix is effective or that my feature works

fix: support disabling options in multi-select

---

projects/observability/src/pages/explorer/explorer.component.test.ts
projects/observability/src/public-api.ts
projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts
projects/observability/src/shared/dashboard/data/graphql/api-calls-count/api-calls-count-data-source-model.ts
projects/observability/src/shared/dashboard/data/graphql/api-calls-count/api-calls-count-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-result.test.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-result.ts
projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/metric-aggregation/metric-aggregation-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/metric-aggregation/metric-aggregation-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/table/explore/explore-table-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/trace/aggregation/trace-metric-aggregation-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/trace/donut/trace-donut-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/trace/donut/trace-donut-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/trace/timeseries/trace-metric-timeseries-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/trace/timeseries/trace-metric-timeseries-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/trace/trace-series-values-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/trace/trace-value-data-source.model.ts
projects/observability/src/shared/dashboard/widgets/top-n/data/top-n-data-source.model.test.ts
projects/observability/src/shared/dashboard/widgets/top-n/data/top-n-data-source.model.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-builder.service.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.test.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-query.ts

feat: explore query builder

---

projects/observability/src/shared/components/radar/tooltip/radial-data-lookup-strategy.ts

In Firefox alone, wrong tooltip was shown for radar chart
- **on a bugfix**: Bug: Wrong tooltip is showing for radar chart #748. For firefox, radialAxisData was not sorted on the basis of axisRadian
Run all test cases using npm run lint && npm run test

fix: wrong tooltip in radar chart in firefox

---

projects/common/src/navigation/ht-route-data.ts
projects/common/src/navigation/ht-route.ts
projects/common/src/navigation/navigation.service.test.ts
projects/common/src/navigation/navigation.service.ts
src/app/config.module.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/index.html

Support route wise page titles
Tested manually. UT added.

feat: support route wise page titles

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
package.json

Updating config to work with already-updated husky version. This will require updating node_modules (`npm ci`)
Ran all git commands using hooks.

chore: update husky config

---

projects/observability/src/shared/components/bar-gauge/bar-gauge.component.scss
projects/observability/src/shared/components/bar-gauge/bar-gauge.component.test.ts
projects/observability/src/shared/components/bar-gauge/bar-gauge.component.ts

Adding Unlimited (infinite) value to Bar Gauge.  
Visual testing:

feat: Adding unlimited value

---

tsconfig.base.json

Added esnext.string to tsconfig libs.

feat: add esnext.string to ts libs

---

projects/observability/src/shared/components/bar-gauge/bar-gauge.component.ts

Adding HTDisplayNumber pipe to Bar Gauge
Visual Testing:

feat: Adding bar gauge htDisplayNumber pipe

---

projects/components/src/link/link.component.ts

This provides an option to open links in a new tab.

feat: add option to open link in new tab

---

projects/components/src/summary-list/summary-list.component.ts

- Changing icon size.
Visual testing

feat: set size of new icons

---

projects/components/src/link/link.component.ts

Reverts hypertrace/hypertrace-ui#1019

Revert "feat: add option to open link in new tab"

---

projects/components/src/navigation/nav-item/nav-item.component.scss
projects/components/src/navigation/nav-item/nav-item.component.ts
projects/components/src/navigation/navigation-list.component.ts
projects/components/src/navigation/navigation-list.module.ts

refactor: adding nav changes

---

projects/components/src/navigation/navigation-list.component.ts

This PR fixes an issue with asynchronously created navItem lists not updating after initial load.

fix: issue with async nav lists not updating correctly

---

projects/components/src/navigation/navigation-list.component.scss

Setting background color for the resize button on nav.
N/A

fix: set background color for resize button

---

projects/observability/src/shared/components/topology/d3/d3-topology.ts
projects/observability/src/shared/components/topology/d3/layouts/custom-tree-layout.ts
projects/observability/src/shared/components/topology/d3/layouts/tree-layout.ts
projects/observability/src/shared/components/topology/renderers/edge/topology-edge-renderer.service.ts
projects/observability/src/shared/components/topology/renderers/node/topology-node-renderer.service.ts
projects/observability/src/shared/dashboard/widgets/topology/edge/curved/entity-edge-curve-renderer.scss
projects/observability/src/shared/dashboard/widgets/topology/edge/curved/entity-edge-curve-renderer.service.ts
projects/observability/src/shared/dashboard/widgets/topology/node/box/entity-node-box-renderer.service.ts

feat: creating a more condensed left to right topology layout

---

package.json
projects/observability/package.json
projects/observability/src/shared/components/cartesian/chart.ts
projects/observability/src/shared/components/cartesian/d3/axis/cartesian-axis.ts

Removing unused type in tickCount variable
Visual testing.

feat: removing unused type in tickCount variable

---

projects/components/src/icon/icon-border.ts
projects/components/src/icon/icon.component.scss
projects/components/src/icon/icon.component.ts
projects/components/src/public-api.ts
projects/components/src/select/select-option.component.ts
projects/components/src/select/select-option.ts
projects/components/src/select/select.component.ts

- Adding border property to icons and select
Visual testing

feat: adding icon properties

---

projects/components/src/table/controls/table-controls.component.test.ts
projects/components/src/table/controls/table-controls.component.ts

Update table search debounce from 200ms to 400ms to reduce api calls.
Manual, updated UT
https://github.com/hypertrace/hypertrace-ui/issues/1072

Increase default debounce

---

projects/common/src/utilities/coercers/date-coercer.ts
projects/common/src/utilities/formatters/date/date-formatter.test.ts
projects/common/src/utilities/formatters/date/date-formatter.ts
projects/common/src/utilities/formatters/date/display-date.pipe.test.ts
projects/common/src/utilities/formatters/date/display-date.pipe.ts
projects/components/src/table/cells/data-parsers/table-cell-timestamp-parser.test.ts
projects/components/src/table/cells/data-parsers/table-cell-timestamp-parser.ts

Dates coming through as strings, even though we have the tools to parse them, are not supported today in the table parser or the date display pipe. This adds that support.
Manual, added UTs

fix: support anything coercer supports for date parsing

---

projects/components/src/radio/radio-group.component.ts
projects/components/src/radio/radio-option.ts

By this, we will be able to pass custom template as well for label.
Local testing done!!

feat: template functionality for radio button label

---

projects/common/src/telemetry/user-telemetry-impl.service.ts

refactor: remove initialize call during registration

refactor: remove initialize call during registration

---

projects/common/src/telemetry/user-telemetry-impl.service.ts

fix: running telemetry methods on initialized list only

fix: running telemetry methods on initialized list only

---

projects/common/src/telemetry/providers/freshpaint/freshpaint-provider.ts
projects/common/src/telemetry/providers/freshpaint/load-snippet/index.d.ts
projects/common/src/telemetry/providers/freshpaint/load-snippet/index.js
projects/common/src/telemetry/user-telemetry-impl.service.test.ts
projects/common/src/telemetry/user-telemetry-impl.service.ts

refactor: adding type and reading from window freshpaint

refactor: adding type and reading from window freshpaint

---

projects/components/src/combo-box/combo-box.component.ts
projects/components/src/filtering/filter-bar/filter-bar.component.ts
projects/components/src/filtering/filter-bar/filter-chip/filter-chip.component.ts

Fixed a couple issues causing bugs in filter bar chip interactions
Verified through unit tests and manual

fix: incorrect focus on editing filter chips

---

projects/components/src/multi-select/multi-select.component.test.ts
projects/components/src/multi-select/multi-select.component.ts

Fixes a bug that prevents trigger label from updating.

Fix multi select view update

---

projects/common/src/preference/preference.service.ts
projects/common/src/utilities/browser/storage/session-storage.ts
projects/components/src/multi-select/multi-select.component.ts
projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

This changes table widget to use sessionStorage instead of localStorage to persist view preferences.

feat: table prefs now use sessionStorage instead of localStorage

---

projects/common/src/navigation/navigation.service.ts
projects/observability/src/pages/explorer/explorer.component.test.ts
projects/observability/src/pages/explorer/explorer.component.ts
projects/observability/src/pages/explorer/explorer.module.ts
projects/observability/src/shared/components/cartesian/chart.ts
projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.ts
projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts

The full explorer query including series, group, limit and interval are now represented in the URL. The allows both bookmarking/sharing queries, as well as navigating back to the explorer after navigating away using regular browser actions.
Manual, updated unit tests + added new.

feat: persist explorer state in url

---

projects/common/src/navigation/navigation.service.test.ts
projects/common/src/navigation/navigation.service.ts
projects/components/src/navigation/navigation-list.service.test.ts
projects/components/src/navigation/navigation-list.service.ts
projects/components/src/public-api.ts
src/app/shared/navigation/navigation.component.test.ts
src/app/shared/navigation/navigation.component.ts

This PR -> https://github.com/hypertrace/hypertrace-ui/pull/969 introduced a change where the common project depends on components project. That should not happen. Refactoring code to avoid that unintended dependency.
Verified with build.

fix: common project should not depend on components project

---

projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

Change column configs to persist to localStorage instead of sessionStorage.

Table use local storage for columns

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
projects/observability/src/pages/explorer/explorer.component.ts

Fixing two separate bugs.
In dev mode, material warns if duplicate columns are being added to a table. We attempt to avoid that in explorer, but the pre-defined keys got out of sync with the pre-defined columns. That needs a better design, this is a quick bandaid until we come back to this with some upcoming work on selectable columns.
Explorer state is captured in the url, but when the group selection changes from a group key to none, it was not removed from the URL. This is because we always merge parameters, and the none state has no representation in the url. Updated to explicitly remove those parameters.
Ran tests and manually verified.

fix: avoid dupe columns, clear group name from url on none

---

projects/components/src/table/controls/table-controls.component.ts

When a single select control was changing, it was emitting an object for its `values` field instead of an array because it was using the same handler.

fix: emit correct shape for single select change

---

projects/observability/src/pages/explorer/explorer.component.test.ts
projects/observability/src/pages/explorer/explorer.component.ts

It will provide preference persistence for panels/sections, present in the explorer on expand and collapse.

feat: persisted expand collapse for explorer panels

---

projects/components/src/table/table.component.scss
projects/components/src/table/table.component.test.ts
projects/components/src/table/table.component.ts

This adds a highlight to selected rows and enables that with multi-select as well.

feat: add row highlighting to table selections

---

projects/dashboards/src/public-api.ts
projects/dashboards/src/widgets/text/text-widget-renderer.component.scss
projects/dashboards/src/widgets/text/text-widget-renderer.component.ts
projects/dashboards/src/widgets/text/text-widget-types.ts
projects/dashboards/src/widgets/text/text-widget.model.ts

Support different styles for title in text-widget
Manually verified.

feat: support styles for text-widget primary text

---

projects/components/src/form-field/form-field.component.scss
projects/components/src/form-field/form-field.component.test.ts
projects/components/src/form-field/form-field.component.ts

fix: make border configurable in form field

fix: make border configurable in form field

---

projects/components/src/radio/radio-group.component.ts

refactor: making radio forms compatible with forms

refactor: making radio controls compatible with forms

---

projects/components/src/datetime-picker/datetime-picker.component.test.ts
projects/components/src/datetime-picker/datetime-picker.component.ts
projects/components/src/time-range/predefined-time.service.ts

Updating the time sometimes changes the date due to timezone issues. The date string was constructed using `toISOString()` method which uses the UTC timezone as seen:
```ts
const date = new Date();  // Thu Dec 09 2021 23:25:27 GMT+0530 (India Standard Time)
date.toISOString(); // 2021-12-09T17:55:27.051Z
```
So if the timeframe is in the range of the user's timezone, the date can change
This PR fixes the issue by replacing the `toISOString()` method for getting the date value.

Fix date picker timezone issue

---

projects/components/src/table/controls/table-controls.component.ts

The logic to apply the filter selections has been left to the consumer of the table control header. This is not intuitive and is often forgotten so pulling that code into the table control component.
Spot tested this on a few table pages and found no issues. Any logic on the consumer side is now redundant, but should have no side effects.

fix: pull applied filter logic into table controls so consumer doesn't have to manage

---

package-lock.json
package.json
projects/components/package.json
projects/components/src/color-picker/color-picker.component.scss
projects/components/src/color-picker/color-picker.component.test.ts
projects/components/src/color-picker/color-picker.component.ts
projects/components/src/color-picker/color-picker.module.ts
projects/components/src/form-field/form-field.component.scss
projects/components/src/public-api.ts
tsconfig.base.json

feat: adding color picker component

feat: adding color picker component

---

projects/components/src/color-picker/color-picker.component.scss
projects/components/src/color-picker/color-picker.component.ts
projects/components/src/combo-box/combo-box.component.ts

feat: Combo box forms

---

projects/components/src/titled-content/titled-content.component.scss

Addresses the issue referenced in https://github.com/hypertrace/hypertrace-ui/issues/1298.
The current styling file had the `regular` and other corresponding classes outside of `footer`.
Moved those inside of `footer` to correct the styling.

Fix: corrected nested styling for `titled-content` component's footer

---

projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts

Fixes hypertrace/hypertrace-ui#1344
- Currently when a typed search parameter is cleared out, an `""` is sent as a parameter in the GraphQL query as referenced in https://github.com/hypertrace/hypertrace-ui/issues/1344.
- This PR checks in case the search parameter is empty and avoids sending an empty `LIKE` parameter.

Bugfix: Prevent empty `LIKE` clause for search parameters

---

projects/components/src/feature-check/if-feature.directive.test.ts
projects/components/src/feature-check/if-feature.directive.ts

After this, will be able to provide else template for `*htIfFeature`, similar to `*ngIf`
Example
```
<ng-container *htIfFeature="state as featureState; else elseTemplate">
<div class="test-div">{{featureState}}</div>
</ng-container>
<ng-template #elseTemplate>
<div class="else-div">Else template</div>
</ng-template>
```
Manual testing done.

feat: providing functionality to use else template in if feature directive

---

projects/common/src/time/time.test.ts
projects/common/src/time/time.ts
projects/components/src/time-picker/time-picker.component.test.ts
projects/components/src/time-picker/time-picker.component.ts
projects/components/src/time-picker/time-picker.module.ts

Fixing Time comparison
Tested locally

fix: Fixing Time picker comparison time in dropdown

---

projects/components/src/navigation/navigation-list.component.scss

There was no scroll when the navigation list height exceeds the viewport height. This PR fixes the issue by adding a
`overflow-y` style prop for the navigation list.

style: add overflow for navigation list

---

projects/components/src/filtering/filter/parser/parsed-filter.test.ts
projects/components/src/filtering/filter/parser/parsed-filter.ts

This fixes the parsing of an attribute whose name is a superset of another attribute's name (e.g. `attrName` and `attrNameOther`). Because the parser is also meant to support cases like `attrName !` where an attribute name is followed by more characters that will eventually become an operator, it previously discarded any extra characters after a successful match. Now, we update it to ensure the following character is non alphanumeric (and thus is not a continuation of the key name). This will allow spaces, partial operators etc. but prevent a match of a different key.
Both E2E and new/existing unit tests.

fix: parser should only match full filter keys

---

projects/components/src/combo-box/combo-box.component.scss
projects/components/src/combo-box/combo-box.component.ts

Add form Control disabled to Combobox
Tested locally.

feat: Add formControl disabled to combo-box

---

projects/common/src/color/color.ts
projects/components/src/label-tag/label-tag.component.scss
projects/components/src/overlay/sheet/sheet-overlay.component.scss

refactor: minor styling changes to shared components

refactor: minor styling changes to shared components

---

projects/observability/src/shared/components/cartesian/cartesian-chart.component.ts
projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget-renderer.component.ts

fix(bug): brush should not be there for cartesian chart if there is no selection handler

fix(bug): brush should not be there for cartesian chart if there is no selection handler

---

projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.test.ts
projects/components/src/multi-select/multi-select.component.ts
projects/components/src/multi-select/multi-select.module.ts

- Adds improved disable support (form integration, remove pointer on disable)
- Adds tooltip for overflow label so they can be viewed without opening multiselect (which isn't possible when disabled)
Action shot:

feat: add minor multiselect improvements

---

projects/components/src/input/input.component.ts

Input component was not resetting on calling `reset()`. Issue was due to CD not running.
Added explicit CD `markForCheck` call.

fix(input): reset on input component not working fix

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
projects/observability/src/shared/dashboard/widgets/table/services/table-widget-columns.service.ts

This change configures all of the Traces table columns to allow quick filtering for the data types that support it.

Make Traces editable columns filterable for all data types that support it

---

projects/graphql-client/src/graphql-request.service.ts

This adds some additional messaging when the GQL response contains errors.

fix: improve query error console messaging

---

projects/components/src/table/table.component.ts

Adding a event emitter for sort change
Tested locally.

feat: table sort change output

---

projects/components/src/label-tag/label-tag.component.scss
projects/components/src/label-tag/label-tag.component.test.ts
projects/components/src/label-tag/label-tag.component.ts
projects/components/src/label-tag/label-tag.module.ts

Adding prefix icon for label tag component

feat: prefix icon for label tag component

---

projects/observability/src/shared/components/explore-query-editor/group-by/explore-query-group-by-editor.component.ts

Whenever we go from group by [any key] to None, query errors out, it is due to `omit(undefined, 'metadata')`
Since this return an empty object and we are only handling `undefined` value

fix(group-by): fixing error while changing the group by from a key to none

---

projects/components/src/collapsible-sidebar/collapsible-sidebar.component.scss
projects/components/src/filtering/filter-bar/filter-chip/filter-chip.service.test.ts
projects/components/src/filtering/filter/builder/filter-builder-lookup.service.test.ts
projects/components/src/filtering/filter/builder/types/boolean-filter-builder.ts

refactor: minor style changes

---

projects/common/src/utilities/formatters/date/date-formatter.test.ts
projects/common/src/utilities/formatters/date/date-formatter.ts

Adding format Full month and year
Example: 2021-08-19 ---> August 2021
Visual testing 

feat: add full month and year formatter

---

projects/components/src/checkbox/checkbox.component.scss
projects/components/src/checkbox/checkbox.component.ts
projects/components/src/table/data/table-cdk-data-source.ts
projects/components/src/table/header/table-header-cell-renderer.component.scss
projects/components/src/table/header/table-header-cell-renderer.component.test.ts
projects/components/src/table/header/table-header-cell-renderer.component.ts
projects/components/src/table/table.component.scss
projects/components/src/table/table.component.ts

Update sort icons and adding checkbox in header cell for multi select

---

projects/components/src/load-async/wrapper/load-async-wrapper.component.ts
projects/components/src/not-found/not-found.component.ts
projects/components/src/notification/notification.component.ts

Add `role=alert` and `data-alert-type="failure"` for components showing error states:
1. Toast Error
2. Load Async Error 
3. Not Found
Selector:
```js
$('[role=alert][data-alert-type="failure"]')
```

Feat | add error selectors

---

projects/components/src/textarea/textarea.component.scss
projects/components/src/textarea/textarea.component.ts
projects/components/src/textarea/textarea.module.ts

Adding textarea disabled style.
Visual testing

feat: adding textarea disabled style

---

projects/common/src/preference/preference.service.ts
projects/common/src/utilities/browser/storage/in-memory-storage.ts

Adds a mechanism to store preferences in memory - for just the current application session.

feat: in memory preferences

---

projects/components/src/filtering/filter/filter-url.service.test.ts
projects/components/src/filtering/filter/filter-url.service.ts

feat: making group by compatible with url

feat: making group by compatible with url

---

src/app/root.module.ts

Telemetry orchestration added without registering the module. This sets up the no-op module.

fix: add empty telemetry module

---

projects/observability/src/shared/dashboard/widgets/trace-detail/data/api-trace-detail-data-source.model.test.ts
projects/observability/src/shared/dashboard/widgets/trace-detail/data/trace-detail-data-source.model.test.ts
projects/observability/src/shared/dashboard/widgets/trace-detail/data/trace-detail-data-source.model.ts

refactor: always use query limits

---

projects/components/src/filtering/filter/parser/filter-parser-lookup.service.test.ts
projects/components/src/filtering/filter/parser/types/in-filter-parser.ts

fix: in filter parser should support string array

fix: in filter parser should support string array

---

projects/observability/src/shared/components/log-events/log-events-table.component.test.ts
projects/observability/src/shared/components/log-events/log-events-table.component.ts

This change removes pagination from the log-event-table as it is unnecessary.

fix: remove pagination from log-event-table

---

projects/assets-library/src/icons/icon-type.ts
projects/components/src/select/select.component.ts
projects/components/src/table/header/table-header-cell-renderer.component.ts

- added a new icon type
- Updated tooltip
- select find item should use `isEqual`. This works for the case when `value` is an object

refactor: minor tooltip and icon changes

---

projects/components/src/table/cells/data-renderers/relative-timestamp/relative-timestamp-table-cell-renderer.component.test.ts
projects/observability/src/shared/components/table/data-cell/exit-calls/exit-calls-table-cell-renderer.component.test.ts

Update tests to use appropriate function to mock directives - this is an error as types are fixed in later ng mock.

test: use correct mock functions

---

projects/components/src/panel/header/title/panel-title.component.scss
projects/components/src/panel/panel.component.scss
projects/components/src/panel/panel.component.ts

- `Background Color` and `Show Border` property added

feat: new properties for panel component

---

projects/common/src/utilities/browser/storage/abstract-storage.test.ts
projects/common/src/utilities/browser/storage/abstract-storage.ts
projects/common/src/utilities/browser/storage/dictionary-storage-impl.test.ts
projects/common/src/utilities/browser/storage/dictionary-storage-impl.ts
projects/common/src/utilities/browser/storage/in-memory-storage.ts

Add the ability to configure storage to use a scope to contain its values, optionally falling back to the global scope. This can be used in several ways - storing by version, storing by user, storing by feature etc.
Added UTs

feat: add storage scoping

---

projects/observability/src/shared/components/donut/donut-builder.service.ts
projects/observability/src/shared/components/donut/donut.component.ts
projects/observability/src/shared/components/donut/donut.ts
projects/observability/src/shared/components/legend/legend.component.scss
projects/observability/src/shared/components/legend/legend.component.test.ts
projects/observability/src/shared/components/legend/legend.component.ts
projects/observability/src/shared/components/utils/d3/d3-visualization-builder.service.ts
projects/observability/src/shared/components/utils/d3/d3-visualization.scss

Adding font size property to legend component and style fix.

feat: adding font size property to legend component and style fix

---

projects/observability/src/shared/graphql/model/schema/filter/id/graphql-id-filter.ts

Parameterize operator for GraphQLIdFilter.

feat: add operator argument to GraphQlIdFilter

---

projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.scss
projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.test.ts
projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.ts
projects/components/src/table/cells/table-cells.module.ts
projects/components/src/x-more/x-more.component.scss

Styling fixes for cell renderers.
Use x-more component in string array cell renderer.
UTs added.

fix(styling): styling fixes for cell renderers

---

projects/components/src/overlay/sheet/sheet-overlay.component.ts

Avoid using globalHeaderHeight for popover height computation.
N/A

fix(sheet overlay): fix height computation for sheet

---

projects/common/src/navigation/navigation.service.ts
projects/components/src/navigation/nav-item/nav-item.component.ts

When navigating with nav items, the selected environment would reset due to it's query params being removed from the nav event. Before TR changes this wasn't an issue because there was no query params in the nav item link. 

Query params resetting on nav item click

---

projects/common/src/time/time-range.service.test.ts
projects/common/src/time/time-range.service.ts

Previously, when loading the app with a time range parameter, the first time we navigate would _always_ trigger a time range change call, whether it was caused by one or not. 
This was because we concat'd two different observables - one to initialize the time range from URL, and another to consume changes from the URL. The change consuming observable always fired the first time since it could not yet tell if it was a change (distinctUntilChanged). That led to the behavior where if the first initializing observable did anything, the first change consuming action would be a duplicate (unless that change happened to be the time range).  If the first initializing observable did nothing (because there was no TR), things worked as expected.
To fix this, we separated out the two subscriptions …

fix: avoid extra emit on deep link

---

projects/common/src/public-api.ts
projects/common/src/utilities/browser/storage/abstract-storage.test.ts
projects/common/src/utilities/browser/storage/abstract-storage.ts
projects/common/src/utilities/browser/storage/local-storage.ts
projects/common/src/utilities/browser/storage/session-storage.ts

This change extends on the functionality added in https://github.com/hypertrace/hypertrace-ui/pull/1517 . In the first PR, the functionality was added, but was not used. Now, an optional late-resolving config can be provided to the local and session storage services to support either config or runtime assignment for the entire application.
Updated existing tests, verified E2E

refactor: allow async config for storage

---

projects/common/src/utilities/formatters/string/highlight.pipe.test.ts
projects/common/src/utilities/formatters/string/highlight.pipe.ts

Highlight pipe uses regex matching to replace strings with corresponding highlight HTML.
This approach fails when the string to be replaced itself is a regex. The regex based matching fails since the method tries to parse it as a string. Hence, escaping reserved regex characters before doing the replacement step.
UT added.

fix: escape regex reserve characters in highlight pipe

---

projects/common/src/utilities/formatters/string/highlight.pipe.test.ts
projects/common/src/utilities/formatters/string/highlight.pipe.ts

Moving the undefined check for highlight config text up in the flow.
Skipping regex matching/replacement logic when highlight config text is empty/undefined.
UT added.

fix: highlight pipe improvements

---

projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.ts

Before this, in multi-select content, all of the content used to scroll including the search bar and select-all button. After this, Only options will scroll.

fix: multi select scroll

---

projects/components/src/color-picker/color-picker.component.ts

Fixing the bug that did not select the color if it did not belong to the color palette previously.
Local testing.

feat: fixing color selection

---

projects/observability/src/shared/graphql/model/schema/filter/id/graphql-id-filter.ts
projects/observability/src/shared/graphql/request/handlers/traces/export-spans-graphql-query-handler.service.test.ts
projects/observability/src/shared/graphql/request/handlers/traces/trace-graphql-query-handler.service.test.ts

feat: use idScope instead of idType for GraphQlIdFilter

---

projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-builder.service.ts
projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.test.ts

Enum scope for explorer was deprecated long ago, updating UI to use string.
Verified E2E

refactor: use string scope for explorer - enum is deprecated

---

projects/observability/src/shared/components/cartesian/d3/axis/cartesian-axis.ts
projects/observability/src/shared/components/cartesian/d3/chart/cartesian-chart.ts

`Bug`: Sometimes we get an empty string for y-axis ticks.
`Fix`: Used the axis width to calculate the tick truncation instead of tickBancWidth

fix: y axis tick truncation for cartesian chart

---

projects/components/src/navigation/navigation.config.ts

Updates the navItemGroup type definition to enable support for hiding nav group.

refactor: nav group type definition change

---

projects/components/src/table/table.component.ts

fix: emitting when a single row is selected

fix: emitting when a single row is selected

---

projects/components/src/tabs/content/tab-group.component.ts

Tabs were not displayed when the content has a `*ngIf` directive or content loads after the tab group initialization.

fix(tab-group): rerender content on change

---

projects/components/src/overlay/sheet/sheet-overlay.component.ts

While using the trigger template, whenever the sheet is open, after clicking escape, the sheet goes away, instead it should collapse.

fix: close on escape for triggered sheet

---

angular.json
src/app/config.module.ts

Fixes #1676 
This is the recommended approach from the [Angular docs][1] as discussed in [this StackOverflow thread][2].
- Run `npm start`
- Warnings are gone from the console logs
[1]: https://material.angular.io/guide/theming#using-a-pre-built-theme
[2]: https://stackoverflow.com/a/50927106/7435656

fix: could not find Angular Material core theme

---

projects/components/src/radio/radio-group.component.ts

Stop propagation from radio group template options fields
Tested locally

fix: Blocking radio group template option propagation

---

projects/common/src/constants/application-constants.ts
projects/common/src/time/page-time-range-preference-service.test.ts
projects/common/src/time/page-time-range-preference.service.ts
src/app/shared/feature-resolver/feature-resolver.service.ts

Allows configuring the page defaults based on the values in the feature flag dictionary map `ApplicationFeature.TenantDefaultTimeRangeMap`.  The page TR defaults now follow the priority: User selected in app -> FF value in the dictionary `map<rootLevelPath, trStringValue>` -> route config define default.

Tenant based custom page TR default support

---

projects/common/src/navigation/navigation.service.test.ts
projects/common/src/navigation/navigation.service.ts

Fetching the route config previously used a "startsWith" match based on an incorrect assumption on how angular's prefix matching worked. It should actually still match full segments. Prefix instead refers to whether later segments invalidate the match. The logic here isn't perfect (corner case scenarios like a multi segment match like `x/y` against a route configs that merge segments like `path: 'x/y'`didn't work and will continue not to), but it's strictly better than what was there previously. We don't generally declare multiple paths in a single route with the exception of path params, which are correctly handled.
Verified E2E, updated unit tests

Fix prefix match routing

---

projects/observability/src/shared/components/cartesian/d3/scale/state/cartesian-stacking-state.ts

fix: setting baseline as 0 when data points are missing

fix: setting baseline as 0 when data points are missing

---

projects/components/src/navigation/navigation-list.component.ts
projects/components/src/navigation/navigation.config.ts

Adding a config to make the nav link item hidden
Local Testing is done

feat: hidden nav link item

---

projects/components/src/navigation/navigation-list.component.test.ts
projects/components/src/navigation/navigation-list.component.ts

PR makes the Privacy policy opens in new tab. 
Earlier result:
Privacy policy opens in the same tab
Expected result from this PR:
Privacy policy should open in new tab
- Added a spectator query to check whether the Component Parameters are matched.

Privacy Policy opening in new tab

---

projects/components/src/file-upload/file-upload.service.ts

Handle file upload error message correctly

fix: file upload error message

---

projects/observability/src/shared/graphql/request/handlers/entities/query/entity/entity-graphql-query-handler.service.ts

Ignore global filters on the entities query when the request is for a single entity.
When a request for a single entity is made with an ID, expectation is that the user is taking an action to view that data deliberately. Global filters that might conflict with this ID based selection should be ignored.
N/A

fix(entity query): ignore global fitlers for single entity query

---

projects/components/src/filtering/filter-bar/filter-chip/filter-chip.service.test.ts
projects/components/src/filtering/filter/builder/filter-builder-lookup.service.test.ts
projects/components/src/filtering/filter/builder/types/string-filter-builder.ts
projects/components/src/filtering/filter/filter-operators.ts
projects/components/src/filtering/filter/parser/filter-parser-lookup.service.ts
projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
projects/observability/src/shared/services/filter-builder/graphql-filter-builder.service.ts

Search input would generally use the `FilterOperator.Like` , which is the regex filter operator. Because of this, you were unable to search with special characters, because they were not escaped. This PR introduces the `FilterOperator.Contains` in order to escape the special characters and treat the string as plain text.
In this PR, we look for the `FilterOperator.Contains` filters and do two things:
1. Transform the value of the filter to escape the special character's, allowing the GQL to treat it as plain text
2. Change the operator type from: `FilterOperator.Contains` to: `FilterOperator.Like`
- This is because the backend doesn't support a plain text field yet, so we transform the regex string, to act like plain text, then pass it to the query as a `FilterOperator.Like`.  This way In …

Add plain text filter operator to escape special chars

---

projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts
projects/observability/src/shared/components/explore-query-editor/series/explore-query-series-editor.component.test.ts
projects/observability/src/shared/components/explore-query-editor/series/explore-query-series-group-editor.component.test.ts
projects/observability/src/shared/graphql/request/builders/specification/explore/explore-specification-builder.ts

Replace text to support alias (ignoring special chars or spaces)
Tested Locally

fix: Group by Response Alias special characters

---

projects/components/src/panel/header/title/panel-title.component.scss
projects/components/src/panel/panel.component.scss

Updated the hover styles to select the complete header instead of just the title section.
- Added `flex:1` to the label container which is the container after the collapse button.

style(panel): update hover style

---

projects/components/src/stepper/stepper.component.scss

Stepper container should only overflow on y axis

fix: stepper container should only overflow on y axis

---

projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.test.ts
projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.ts

Add empty value template for string array table cell renderer
- This takes care of cell value as `undefined`, `null`, and `[]` and save the code with possible null pointer exceptions.
- It shows `-` when a value is empty

fix: add empty value template for string array table cell renderer

---

projects/components/src/viewer/code-viewer/code-viewer.component.scss
projects/components/src/viewer/code-viewer/code-viewer.component.test.ts
projects/components/src/viewer/code-viewer/code-viewer.component.ts

Adding multiple ways to highlight a code line
- String (Already Present)
- String Array (New)
- RegExp (New)
Local testing is done and added tests for newer support

feat: adding multiple ways to highlight a code line

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.ts

Default sort is on startTime, extra sort on endTime is overriding the default sort even though endTime column not shown.

fix: remove sort from hidden column

---

projects/components/src/overlay/sheet/default-sheet-ref.ts

Currently, Sheet's `closed$` doesn't get updated when `popoverRef.close()` happens from the `SheetOverlayComponent`.
This change will allow that to happen

fix: update close subject in the sheet when popover gets closed

---

projects/common/src/navigation/navigation.service.ts
projects/common/src/time/time-range.service.ts

2 Changes
1. We've had a long standing issue where two different calls to add query params will cause the first to be ignored (because it cancels the nav in flight and starts a new one, so the query params don't get merged. Now, we hold query params until a nav finishes, and if another request arrives, we merge the prior in.
2. If time range refresh is called very early in app bootstrap, it leads to an error as the time range hasn't been initialized yet. Instead, treat it as a no-op.

fix: allow writing query params while nav in flight

---

projects/common/src/navigation/navigation.service.ts

Fixed the tracking of first navigation (used to handle in-app back behavior), to ignore if we update the URL without changing history. This was previously causing erroneous back navigation out of the app.
Local E2E

fix: don't count a navigation until history change

---

projects/components/src/multi-select/multi-select.component.scss
projects/components/src/multi-select/multi-select.component.ts

The border was misplaced and created extra space that didn't fit properly with the other components in the library.
Tested Locally
Old:
New: 

fix: Adapt the height of the multi-select component with other components

---

projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.ts
projects/components/src/table/cells/table-cells.module.ts

This PR adds a limit to StringArrayCellRenderer tooltip items. Currently, if a large size array is supplied to the renderer it hangs up the screen in order to render all the items in tooltip on hover.

fix: added limit to StringArrayCellRenderer tooltip

---

projects/observability/src/shared/components/topology/d3/d3-topology.ts
projects/observability/src/shared/components/topology/topology.ts

Added a configuration to disable the tooltip on hover for topology nodes and edges.

feat: disable tooltip on hover for topology

---

projects/components/src/color-picker/color-picker.component.ts

Adds input config option to color picker to disallow de-selecting current element, and only allow change selection to another option

refactor: no deselect mode for color picker

---

projects/components/src/file-upload/file-upload.service.ts

This adds a way to show notification conditionally when `showNotification` is true (defaulted to true)
Manual testing is done locally.

fix: conditional file upload notifications

---

projects/components/src/radio/radio-group.component.ts

`writeValue` in radio button should just update the state of the component. But it's also emitting a change again. The change event should only be triggered when the change is done from within a component and not from outside (by the form API).

fix(radio-group): write value bug fix

---

projects/components/src/stepper/stepper.component.scss

Add a z-index of the actions button.
When placing tables inside stepper, the action buttons get hidden because the table header have a `z-index` of `10`

style(stepper): add z-index for stepper actions

---

projects/components/src/radio/radio-group.component.scss
projects/components/src/radio/radio-group.component.ts
projects/components/src/radio/radio-option.ts
projects/components/src/radio/radio.module.ts

Added info icon support within a radio option in `ht-radio-group`.

feat: added info icon support in radio option

---

projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.test.ts
projects/observability/src/shared/graphql/model/metadata/attribute-metadata.ts
projects/observability/src/shared/services/metadata/handler/metadata-graphql-query-handler.service.test.ts
projects/observability/src/shared/services/metadata/handler/metadata-graphql-query-handler.service.ts

Adds isCustom field to metadata api.

Add support for isCustom field to metadata api

---

projects/observability/src/shared/graphql/request/builders/specification/specification-builder.ts

Some attributes have the possibility of '-' in their name, hence why this is needed

Remove non-word characters from entities query alias

---

projects/observability/src/shared/graphql/request/builders/specification/specification-builder.test.ts
projects/observability/src/shared/graphql/request/builders/specification/specification-builder.ts

Use the query alias for `extractFromServerData()` property of specifications

Use query alias on server data extraction

---

projects/common/src/public-api.ts
projects/common/src/utilities/angular/pipes/index.ts
projects/common/src/utilities/angular/pipes/is-nil/is-nil-pipe.module.ts
projects/common/src/utilities/angular/pipes/is-nil/is-nil.pipe.ts
projects/components/src/summary-value/summary-value.component.ts
projects/components/src/summary-value/summary-value.module.ts
projects/observability/src/shared/components/span-detail/span-detail.component.ts
projects/observability/src/shared/components/span-detail/span-detail.module.ts

- Component errors out when the `tabs` array is empty. Added extra check to prevent change of tabs if the tabs array is empty.
- Added no data message for span detail if there is no tabs.
- Summary value doesn't render if the value provided is `0`

fix(span-detai): error handling if tabs array is empty

---

projects/common/src/utilities/angular/pipes/extract-value/extract-values-pipe.module.ts
projects/common/src/utilities/angular/pipes/extract-value/extract-values.pipe.test.ts
projects/common/src/utilities/angular/pipes/extract-value/extract-values.pipe.ts
projects/common/src/utilities/angular/pipes/index.ts

A utility pipe that facilitates easy extraction of individual values for a property field from an array of objects.
Sample usage
```
...
public arrayOfObjects = [{x: 1, y:2}];
...
```
```
...
<some-component [values]="this.arrayOfObjects | htExtractValues: 'x'"></some-component>
...
```
UT added.

feat: value extractor pipe

---

projects/components/src/modal/modal-container.component.scss

Center align modal header text.
N/A

fix: center align modal header text

---

projects/components/src/radio/radio-group.component.ts

`ht-radio-group` loses context when a change event triggers inside any complex `radio-option` template. For eg. lets say we have a `ht-input` as part of the radio option template, in that case on any update inside `ht-input` causes radio group to lose context.
`mat-radio-group` emits event on any change that happens inside `radio-option`. Hence update inside `label-template` is considered as a `change` event, but option is not really changed. 
On this event, `event.value` is not present that is being applied inside `onRadioChange`, hence context is lost.
Added a nil check before applying `event.value`.

fix: added check for event value on radio option change

---

projects/components/src/time-picker/time-picker.component.scss
projects/components/src/time-picker/time-picker.component.ts

Add ability to customize the size of **Time Picker** component.
Changes made so that current usages won't be affected:
Current size -> `32px` 
Default Size -> `TimePickerSize.Small` -> `32px`

feat(time-picker): add size customization

---

projects/components/src/overlay/overlay.service.test.ts
projects/components/src/overlay/overlay.service.ts
projects/components/src/overlay/sheet/sheet.ts

This PR adds a configurable backdrop option to the sheet popover component. When configured, the sheet popover component will render as normal, but the user will not be able to interact with any components they can see "behind" the popover sheet, eg: the environment selector.
The sheet popover  can be configured with a visible, opaque grey backdrop, or an invisible backdrop. By default, the backdrop is not created when opening a sheet popover, and there should be no regression.
I added tests to the `popover.service.ts` to ensure the popover is not applied …

feat: add backdrop to sheet popover

---

projects/components/src/stepper/stepper.component.ts

*Next* button disabled state check logic updated to allow navigation when the form is `VALID` or `DISABLED`.

feat(stepper): enabled next when form is disabled state

---

projects/components/src/table/table.component.scss

Table was not respecting `min-height` added to parent.

style(table): table not respecting min-height

---

projects/components/src/panel/collapsed-body/panel-collapsed-body.component.ts
projects/components/src/panel/panel.component.scss
projects/components/src/panel/panel.component.test.ts
projects/components/src/panel/panel.component.ts
projects/components/src/panel/panel.module.ts

`UseCase` -> We want to have some minimized content when the Panel is collapsed.
`Implementation` -> Added a new `ht-panel-collapsed-body` component

feat: add panel collapsed body component

---

projects/graphql-client/src/utils/builders/request/graphql-request-builder.ts

Prevents generating and Argument with an empty object '{}' when the argument is null.
Tested locally

fix: Fixing Null argument in GraphqlRequestBuilder

---

projects/components/src/icon/icon.component.test.ts
projects/components/src/icon/icon.component.ts

mat-icon component does not render correctly when we switch from svg icon to ligature icon in place.
We get a blank element instead of a ligature icon.
Using separate instances of mat-icon inside the ht-icon component to isolate this problem and supply only relevant values to each usage.
After
https://user-images.githubusercontent.com/63222211/220830360-068e39f7-6e22-45df-9ea6-2df07419c49b.mov
Before
https://user-images.githubusercontent.com/63222211/220830483-bbcb5f83-6950-4f4a-af59-ce01dc151252.mov
Tested locally. Added UTs.

fix: separate mat-icon implementation for svg and ligature

---

projects/observability/src/shared/components/span-detail/span-detail.component.scss

`.summary-container` was expanding the summary items to take full width of span detail,  because of the default flex behavior and all the extra width space the summary items were given, this resulted in tooltips being oddly placed.  Aligning items to flex start fixes this.

refactor: align summary container for correct placement of tooltips

---

projects/common/src/time/page-time-range-preference.service.ts
projects/common/src/time/time-range.service.ts

feat: setting default TR from current url when ff is disabled

feat: setting default TR from current url when ff is disabled

---

projects/components/src/navigation/navigation-list.component.ts

If the `navItems` is receieved as `null`, it would break the UI.

fix(nav-list): null handling

---

projects/common/src/time/interval-duration.service.test.ts
projects/common/src/time/interval-duration.service.ts
projects/observability/src/pages/explorer/explorer.component.test.ts
projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.test.ts
projects/observability/src/shared/components/explore-query-editor/interval/explore-query-interval-editor.component.test.ts

Sub-minute granularity isn't used and adds confusion for end user (as axes are always printed without seconds).

refactor: remove second interval granularity

---

projects/components/src/load-async/wrapper/load-async-wrapper.scss

Fixing regression from https://github.com/hypertrace/hypertrace-ui/pull/2075 - this stylesheet was previously unreferenced, but the new usage introduced a class that breaks styling.

fix: old class introduced unintentionally

---

projects/components/src/button/button.component.scss

Fixing Accessibility color in buttons

fix: fixing accessibility color in button

---

projects/components/src/table/table.component.ts

refactor: calling disconnect when changing datasource and on destroy

refactor: calling disconnect when changing datasource and on destroy

---

projects/assets-library/assets/styles/_color-palette.scss
projects/components/src/button/button.component.scss

Update destroy button color to support accessibility
Locally tested

fix: update destroy button color to support accessibility

---

projects/assets-library/assets/styles/_interaction.scss
projects/common/src/color/color.ts
projects/components/src/modal/modal-container.component.ts

Adding aria-label and updating color and opacity value
Tested locally

fix: Updating color and adding aria label into modal icon to support accessibility

---

projects/assets-library/assets/styles/_color-palette.scss
projects/components/src/textarea/textarea.component.ts

Updating blue color to support accessibility and adding ariaLabel into textArea
Tested Locally

fix: Update blue color and add textarea aria-label

---

projects/components/src/table/table.component.ts

This fixes the re-rendering for the detailed content if any other row is expanded.
`Current Behaviour`
Currently, if we have a table of type `detail` and we expand a row, the first one works fine but if we expand another row then it renders both the rows. That means it will always render all the previously expanded rows if we expand any other rows.
`FIx`
There are checks needed to fix this.
1. Selections change should not be triggered if current and previous both selections are empty.
2. The rowChange emission should only happen when the table of `tree` type, since it causes the whole table to re-render
Manual testing is done.

fix: table detail content rendering

---

projects/assets-library/assets/styles/_color-palette.scss

update red risk color to support accessibility
Locally tested

fix: update red risk color to support accessibility

---

projects/components/src/copy-to-clipboard/copy-to-clipboard.component.ts
projects/components/src/copy-to-clipboard/copy-to-clipboard.module.ts

use click event blocker around copy to clipboard component.
Clicks in copy to clipboard control should never be propagated upstream.

fix: use click event blocker around copy to clipboard component

---

projects/components/src/select/select.component.ts

We use `!` on `allOptions$` but it is assigned a value only in the `ngAfterContentInit` lifecycle.
When the component gets initialized, if `writeValue` is called, then there is this piece of code which runs:
```ts
private buildObservableOfSelected(): Observable<SelectOption<V> | undefined> {
return this.allOptions$.pipe(
switchMap(items => merge(of(undefined), ...items.map(option => option.optionChange$))),
map(() => this.findItem(this.selected))
);
}
```
Here `this.allOptions$` will be `undefined` in the start and hence throws error. Having a default `EMPTY` value for `allOptions$` doesn't break the code.

fix(select): removed assertion

---

projects/components/src/table/table.component.ts

This got removed mistakenly with the last PR, so adding it back again

fix: adding hide column functionality back

---

projects/components/src/table/cells/table-cell-injection.ts
projects/components/src/table/cells/table-cell-renderer-base.ts
projects/components/src/table/table-api.ts

- Add extra `options` prop to the `TableColumnConfig`
- Use it to pass extra data to the renderers which can then be used for customizing the renderers.

feat(table): add options to allow customization of cell renderers

---

projects/observability/src/shared/components/topology/renderers/edge/topology-edge-renderer.service.ts
projects/observability/src/shared/dashboard/widgets/topology/edge/curved/entity-edge-curve-renderer.scss
projects/observability/src/shared/dashboard/widgets/topology/edge/curved/entity-edge-curve-renderer.service.ts
projects/observability/src/shared/dashboard/widgets/topology/node/box/entity-node-box-renderer.scss
projects/observability/src/shared/dashboard/widgets/topology/node/box/entity-node-box-renderer.service.ts

For large data, the topology chart is taking a lot of time to render.
We are computing the text widths for node and edge from DOM and updating the properties in the same flow which takes a lot of time to be done.
`For Edge` -> We used the monospace font so that we know each character would have the same width. Used that to define the `getCharWidth` function.
`For Node` -> Similar pattern as edge. But didn't use monospace just defined an average char width, which works well.

fix: topology chart rendering

---

projects/components/src/paginator/paginator.component.ts

Paginator should reset to first page only if totalItems count changed.

fix: paginator -> reset to first page only if totalItems count changed

---

.eslintrc.json

Eslint no-console rule to disallow console logging
Allow only warnings and errors.

fix: disallow console logging - eslint rule

---

projects/components/src/select/select.component.ts
projects/components/src/table/controls/table-controls.component.ts

Fixing empty option bug got from select in table controls.
Tested locally

fix: Fixing table controls options bug

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
projects/observability/src/shared/components/cartesian/d3/legend/cartesian-legend.ts
projects/observability/src/shared/dashboard/data/graphql/table/spans/spans-table-data-source.model.ts

Fix spams redirection (using traceID) and remove filters from legends that show no possible options
Locally Tested

feat: converts trace ID visible in spam table

---

projects/components/src/menu-dropdown/menu-dropdown.component.ts

Previously, we were using the length of the query list to determine whether the menu is active. This means if it changes (either from or to zero items, for example when using an ngIf with an async pipe), it won't be updated with on push change detection. Switched to a more robust approach here.

fix: support async rendered menu items

---

projects/observability/src/shared/components/explore-query-editor/order-by/explore-query-order-by-editor.component.ts

Removing rate sec/min from Aggregations in Traces.
Locally tested

feat: Removing rate sec/min from aggregations

---

projects/components/src/splitter/splitter.component.scss
projects/components/src/splitter/splitter.component.ts

Splitter fixes

---

projects/components/src/splitter/splitter.component.ts

fix: splitter max height

---

projects/components/src/table/table.component.test.ts
projects/components/src/table/table.component.ts

This reverts commit 1e8d426.
[Please include a summary of the change, motivation and context.](fix: two reverts to undo the recent changes to column configs emission in table)

fix: two reverts to undo the recent changes to column configs emission in table

---

projects/components/src/load-async/load-async.directive.test.ts
projects/components/src/load-async/load-async.directive.ts
projects/components/src/load-async/load-async.service.ts
projects/components/src/load-async/wrapper/load-async-wrapper.component.ts

Add strong typing support for `*htLoadAsync` directive.

feat(load-async): add typing

---

projects/components/src/download-file/service/file-download.service.ts
projects/components/src/table/cells/csv-generators/table-cell-timestamp-csv-generator.test.ts
projects/components/src/table/cells/csv-generators/table-cell-timestamp-csv-generator.ts
projects/components/src/table/table-csv-downloader.service.test.ts
projects/components/src/table/table-csv-downloader.service.ts
projects/components/src/table/table.component.test.ts
projects/components/src/table/table.component.ts
projects/components/src/table/table.service.ts

Improvements to table CSV download flow.
1. Add optional input to table for CSV download configs.
2. Use limit from the above for download data query. If limit is unavailable, default to 1000.
3. Use the filename from config. If unavailable, use fallback logic using table ID.
4. For column keys, preference order is column title -> column name -> column id
5. Update timestamp csv generator.

feat: improvements to table csv download logic

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.ts

1. Changing scope of visualization build method.
2. Add a new `getImplicitFilters` method in the data source.

fix: explorer builder updates

---

projects/components/src/filtering/filter/parser/parsed-filter.ts

Fixing Attribute's subpath when they start with colon
Example: `Request Headers.:example`
Locally tested

fix: fixing attribute's subpath starting with colon

---

projects/components/src/file-upload/file-upload.component.test.ts
projects/components/src/file-upload/file-upload.component.ts

File type validation in the browser is not reliable. So instead of stopping the flow, we show an **Info** toast and let the user proceed.

feat(file-upload): show info toast when diff file type is uploaded

---

projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.ts
projects/observability/src/shared/dashboard/data/graphql/explore/explore-result.ts
projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/axis/cartesian-axis.model.ts

Supporting Aggregation queries in Visualization
Locally Tested.

feat: supporting aggregation queries in visualization

---

projects/components/src/table/data/table-cdk-data-source.ts

Caching on table was preventing requests from firing when the request changed

fix: table should not cache if filter or sort changes

---

projects/components/src/search-box/search-box.component.scss
projects/components/src/search-box/search-box.component.test.ts
projects/components/src/search-box/search-box.component.ts

The collapsable behaviour of the search box was tied to whether search history was enabled or not.
Now added a separate input `collapsable` which can be set to `true` to make the search box collapsable and vice versa.
Search history is now independent of this.

Fix: Separate collapsable and search history behaviour

---

projects/observability/src/shared/dashboard/data/graphql/topology/topology-data-source.model.test.ts
projects/observability/src/shared/dashboard/data/graphql/topology/topology-data-source.model.ts
projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.ts

1. Provide a way to pass entity-specific edge and node specifications to the topology

fix: topology data source updates

---

projects/components/src/filtering/filter/filter-url.service.ts

Expose a util method from `FilterUrlService`.

feat(filter): expose a method
