hypertrace/hypertrace-ui

- projects/observability/src/shared/components/card-list/card-list.component.scss
> feat(style): update card border radius

- projects/observability/src/pages/apis/api-detail/api-detail-breadcrumb.resolver.test.ts
- projects/observability/src/pages/apis/api-detail/api-detail-breadcrumb.resolver.ts
- projects/observability/src/shared/constants/entity-metadata.ts
- src/app/entity-metadata.ts
Make endpoint list crumb clickable
> feat(api detail breadcrumbs): Make endpoint list crumb clickable

- projects/observability/src/shared/components/topology/d3/interactions/zoom/topology-zoom.ts
Fixes zoom drag on firefox browser
> fix: checking if touch event exist on the browser

- projects/observability/src/shared/dashboard/widgets/top-n/data/top-n-data-source.model.ts
> Isolate top-n query

- projects/observability/src/public-api.ts
Export Top N Chart from observability module
> feat: export Top N Chart from observability module

- projects/observability/src/public-api.ts
Export service overivew dashboard from observability module.
> fix: export service overview dashboard

- Dockerfile
- conf/default.conf
- Added `default.conf` for nginx as part of Dockerfile. 
- This will help reducing down configs for docker-compose setup.
> added default nginx config for hypetrace-ui

- projects/observability/src/public-api.ts
> feat: export entity renderer module

- src/app/home/home.dashboard.ts
Update submodule.
Use the new greeting label in home dash.
> fix: update greeting widget in home dash

- projects/distributed-tracing/src/shared/services/metadata/metadata.service.ts
- projects/observability/src/public-api.ts
- projects/observability/src/shared/graphql/request/builders/selections/observability-specification-builder.ts
- projects/observability/src/shared/graphql/request/builders/specification/entity/entity-specification-builder.test.ts
- projects/observability/src/shared/graphql/request/builders/specification/entity/entity-specification-builder.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-builder.service.ts
Add support to fetch additional attributes for entity.
> feat: add support to fetch additional attributes for entity

- src/app/home/home.dashboard.ts
> fix: fix typo in cartesian widget title

- projects/components/src/public-api.ts
chore: export beta tag component and module
> chore: export beta tag component and module

- projects/components/src/overlay/sheet/sheet-overlay.component.scss
Removing duplicate CSS rules
NA
> fix: remove duplicate css rules

- projects/components/src/modal/modal-container.component.scss
- projects/components/src/modal/modal.ts
Medium size definition for modal container
Manually tested. Unit test verifying application of correct class already exists.
> feat: add medium size for modal

- projects/components/src/table/cells/data-parsers/table-cell-icon-parser.ts
- projects/components/src/table/cells/data-renderers/icon/icon-table-cell-renderer.component.test.ts
- projects/components/src/table/cells/data-renderers/icon/icon-table-cell-renderer.component.ts
Adds label to the icon cell renderer component
Tested via unit tests and verifying the label working manually on the UI
> chore(icon-table-cell-renderer): add label on icons

- projects/distributed-tracing/src/shared/dashboard/data/graphql/specifiers/field-specification.model.ts
- projects/distributed-tracing/src/shared/graphql/request/builders/specification/specification-builder.test.ts
- projects/distributed-tracing/src/shared/graphql/request/builders/specification/specification-builder.ts
Adding a field specification model
> feat: adding a field specification model

- projects/components/src/public-api.ts
Exporting feature pipe and directive for test mocking
> feat: export feature pipe and directive

- projects/components/src/public-api.ts
- projects/observability/src/public-api.ts
- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.test.ts
- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.ts
Adding custom icon support to entity display
> refactor: adding custom icon support to entity

- projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-base.model.ts
- projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget.model.ts
- projects/observability/src/pages/apis/services/services-list.dashboard.ts
> Move pageable

- projects/distributed-tracing/src/shared/dashboard/data/graphql/filter/graphql-id-scope-filter.model.ts
- projects/distributed-tracing/src/shared/dashboard/data/graphql/graphql-data-source.module.ts
> feat: id scope filter model

- .circleci/config.yml
- build.gradle.kts
addresses https://github.com/hypertrace/hypertrace/issues/19 & https://github.com/hypertrace/hypertrace/issues/22 
Please read discussion here: https://github.com/hypertrace/attribute-service/pull/30
NA
> updates release workflow and gradle plugin version

- projects/common/src/color/color.ts
> feat: add new color constants

- projects/common/src/utilities/formatters/duration/duration-formatter.test.ts
- projects/common/src/utilities/formatters/duration/duration-formatter.ts
Update duration formatter to compute durations of >24 hours
Unit tests added
NA
> feat: update duration formatter to compute days

- projects/common/src/public-api.ts
Export display duration pipe in common module.
N/A
> fix: export display duration pipe

- projects/components/src/public-api.ts
Exporting core table cell parser type
> chore: export core table cell parser type

- projects/components/src/public-api.ts
> chore: export noop parser

- projects/components/src/notification/notification.service.ts
return EMPTY after failure notification
> fix: return EMPTY after failure notification

- projects/components/src/table/table.component.scss
Update z-index of table header row
> style: update z-index of table header row

- projects/observability/src/shared/components/cartesian/cartesian-chart.component.ts
- projects/observability/src/shared/components/cartesian/chart-builder.service.ts
Renderer2 can't be injected into services. Moving to component.
> feat: change renderer2 injection

- projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-builder.service.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-handler.service.test.ts
- projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.test.ts
- projects/observability/src/shared/graphql/request/handlers/explore/explore-graphql-query-handler.service.ts
- projects/observability/src/shared/graphql/request/handlers/util/handler-util.ts
Removing filter on api discovery state
> refactor: remove filter on api discovery state

- projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
- projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
The click handlers on explorer were inconsistent between columns (aside: we should introduce a row-level click handler so this is not an issue)
Unit tests, also manually verifiied
> fix: match explorer click handlers

- projects/common/src/utilities/lang/lang-utils.ts
This check comes up a lot when looking at strings passed in as Inputs() to components.
> feat: add util const to check for empty strings

- projects/components/src/button/button.component.scss
- projects/components/src/button/button.component.test.ts
- projects/components/src/button/button.component.ts
- projects/components/src/button/button.ts
- projects/components/src/copy-shareable-link-to-clipboard/copy-shareable-link-to-clipboard.component.ts
- projects/components/src/copy-to-clipboard/copy-to-clipboard.component.ts
- projects/components/src/modal/modal-container.component.ts
- projects/components/src/open-in-new-tab/open-in-new-tab.component.ts
- projects/components/src/time-range/time-range.component.ts
- projects/components/src/titled-content/titled-content.component.ts
- projects/observability/src/shared/components/label-detail/label-detail.component.ts
Updated ButtonSize by using a 32px size to replace Small.
Changed default to Small 32px to match the Medium 32px that we had previously.
Mapped:
* Medium 32px -> Small 32px
* Small 24px -> ExtraSmall 24px
* ExtraSmall 28px -> Tiny 28px
> Update button sizes

- projects/assets-library/assets/styles/_font.scss
> chore: new smaller subtitle mixin

- projects/components/src/modal/modal-container.component.scss
- projects/components/src/modal/modal.ts
> feat: medium wide modal

- projects/assets-library/src/icons/icon-type.ts
Just adding a new icon type to our shared constant
> chore: add new icon for remove circle

- projects/observability/src/shared/components/bar-gauge/bar-gauge.component.ts
> fix: remove unused code

- projects/distributed-tracing/src/shared/dashboard/data/graphql/graphql-data-source.module.ts
Adding field specification model to graphql module
> refactor: adding field specification model to graphql

- build.gradle.kts
Updates gradle docker plugin to bring in support from detecting branch name in github actions env.
> chore: bump docker publish plugin for gha support

- projects/distributed-tracing/src/shared/components/span-detail/call/body/span-detail-call-body.component.ts
- projects/distributed-tracing/src/shared/components/span-detail/call/headers/span-detail-call-headers.component.ts
- projects/distributed-tracing/src/shared/components/span-detail/headers/title/span-detail-title-header.component.ts
- projects/distributed-tracing/src/shared/components/span-detail/tags/span-tags-detail.component.ts
- projects/distributed-tracing/src/shared/dashboard/widgets/span-detail/span-detail-widget-renderer.component.ts
- projects/distributed-tracing/src/shared/dashboard/widgets/trace-detail/trace-detail-widget-renderer.component.ts
- projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall-widget-renderer.component.ts
- projects/distributed-tracing/src/shared/dashboard/widgets/waterfall/waterfall/span-name/span-name-table-cell-renderer.component.ts
- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.ts
- projects/observability/src/shared/dashboard/widgets/topology/edge/curved/entity-edge-curve-renderer.service.ts
- projects/observability/src/shared/dashboard/widgets/topology/node/box/entity-node-box-renderer.service.ts
- projects/observability/src/shared/dashboard/widgets/topology/tooltip/topology-entity-tooltip.component.ts
refactor: adding sensitive data attribute to certain fields
> refactor: adding sensitive data attribute to certain fields

- projects/observability/src/shared/components/cartesian/d3/scale/cartesian-scale-builder.ts
- projects/observability/src/shared/components/cartesian/d3/scale/cartesian-scale.ts
> fix: spelling

- src/environments/environment.ts
> fix: port number

- projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-select-filter.model.ts
Allow turning off sort for dropdown list if user already sorted.
> feat: add ability to turn off sorting for table select filters

- projects/assets-library/assets/styles/_layout.scss
- projects/components/src/table/table.component.scss
Fixes for some table scrolling issues
> fix: table scrolling issues

- projects/components/src/overlay/sheet/sheet-overlay.component.ts
Set popover height correctly based on position
> fix: set popover height correctly based on position

- projects/components/src/modal/modal-container.component.ts
- projects/components/src/modal/modal.service.test.ts
- projects/components/src/modal/modal.ts
- projects/components/src/overlay/sheet/sheet-overlay.component.test.ts
- projects/components/src/overlay/sheet/sheet-overlay.component.ts
- projects/components/src/overlay/sheet/sheet.ts
- projects/components/src/popover/popover.ts
- add option to close sheet overlay with esc key
> feat(sheet-overlay): close overlay on esc key press

- projects/common/src/time/time-range.service.ts
All data listened to refresh through the changes in time range currently. ideally, we'd have a separate refresh service that is decoupled from the specific causes of refresh, but given the scope of such a change, this will allow us to trigger refreshes that are not tied to the current time range.
Visually verified
> refactor: expose refresh method from time range service

- projects/components/src/multi-select/multi-select.component.ts
refactor: updating label for "All"
> refactor: updating label

- projects/components/src/select/select-control-option.component.ts
- projects/components/src/select/select.component.test.ts
- projects/components/src/select/select.component.ts
- projects/components/src/select/select.module.ts
Support control options in select.
UTs added.
> feat: support control options in select

- projects/components/src/table/controls/table-controls.component.ts
> fix: remove unused code for table control output

- projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/band.model.ts
- projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget.model.ts
Add more json configurable properties to Bands.
> More user defined band properties

- projects/components/src/public-api.ts
> chore: export string cell parser

- projects/common/src/color/color.ts
- projects/components/src/select/select.component.scss
- projects/components/src/select/select.component.ts
Consume option's iconColor in select component.
Styling adjustments.
Defining few new colors.
> feat: support icons with custom colors in select

- projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget.model.ts
Add an additional model property to cartesian widget to allow band data fetching to be disabled.
> feat: add property to cartesian widget to allow disabling band fetches

- projects/observability/src/pages/apis/api-detail/metrics/api-metrics.component.ts
- projects/observability/src/pages/apis/api-detail/metrics/api-metrics.dashboard.ts
- projects/observability/src/pages/apis/api-detail/metrics/api-metrics.module.ts
- projects/observability/src/pages/apis/api-detail/overview/api-overview.dashboard.ts
- projects/observability/src/pages/apis/service-detail/metrics/service-metrics.component.ts
- projects/observability/src/pages/apis/service-detail/metrics/service-metrics.dashboard.ts
- projects/observability/src/pages/apis/service-detail/overview/service-overview.dashboard.ts
- projects/observability/src/public-api.ts
- projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget.model.ts
Added configuration for cartesian health bands to overview and metric dashboards. Turned off by default.
> feat: enable metric health bands

- projects/distributed-tracing/src/shared/dashboard/dashboard-wrapper/navigable-dashboard.component.ts
Add variables input to navigable dashboard component.
> feat: add variables input to navigable dashboard comp

- projects/assets-library/assets/icons/sort.svg
- projects/assets-library/src/icons/icon-library.module.ts
- projects/assets-library/src/icons/icon-type.ts
> feat(icon): add new icon - sort

- projects/observability/src/pages/apis/endpoints/endpoint-list.dashboard.ts
Add column for call count to endpoint list
> feat: add column for call count to endpoint list

- projects/components/src/public-api.ts
Expose timestamp cell parser for use in other modules
> refactor: expose timestamp cell parser

- projects/dashboards/src/public-api.ts
- projects/distributed-tracing/src/public-api.ts
> feat: export table models

- projects/assets-library/assets/styles/_interaction.scss
- projects/components/src/button/button.component.scss
- projects/components/src/menu-dropdown/menu-dropdown.component.scss
- projects/components/src/menu-dropdown/menu-item/menu-item.component.scss
- projects/components/src/multi-select/multi-select.component.scss
- projects/components/src/select/select.component.scss
- projects/components/src/toggle-button-group/button/toggle-button.component.scss
- projects/observability/src/shared/components/explore-query-editor/limit/explore-query-limit-editor.component.scss
Disable is inconsistent across the product, sometimes disabling the cursor and in other places not. This makes a shared mixin to behave more consistently (specifically in select component)
Existing unit tests, visual verification
> chore: make disable consistent across components

- projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
- projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
- projects/observability/src/pages/explorer/explorer.component.test.ts
- projects/observability/src/public-api.ts
- projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.test.ts
- projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.ts
- projects/observability/src/shared/dashboard/data/graphql/explore/explore-result.test.ts
- projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.test.ts
- projects/observability/src/shared/dashboard/data/graphql/explorer-visualization/explorer-visualization-cartesian-data-source.model.ts
- projects/observability/src/shared/dashboard/data/graphql/observability-graphql-data-source.module.ts
- projects/observability/src/shared/dashboard/widgets/charts/cartesian-widget/cartesian-widget.model.ts
> feat: adding a generic explore cartesian group by ds

- projects/observability/src/public-api.ts
refactor: exporting cartesian result
> refactor: exporting cartesian result

- projects/components/src/search-box/search-box.component.scss
search box should use full width
> fix: search box should use full width

- projects/common/src/utilities/formatters/time/display-time-ago.pipe.ts
- projects/components/src/select/select.component.scss
- projects/components/src/table/controls/table-controls.component.scss
> fix: some styling issues

- projects/observability/src/pages/apis/api-detail/traces/api-trace-list.dashboard.ts
- projects/observability/src/pages/apis/service-detail/traces/service-trace-list.dashboard.ts
Adding click handler to newly added exit calls column
> fix: add click handler to exit calls column

- projects/components/src/public-api.ts
Adding Toggle Switch Size Enum to public-api
It's not necesary
> feat: adding toggle switch size enum to public-api

- projects/components/src/table/table.component.scss
- projects/components/src/table/table.component.ts
Reverts hypertrace/hypertrace-ui#668
> Revert "refactor: fixing table css so that it can work inside flex container"

- .prettierignore
- jest.config.js
- package-lock.json
- package.json
- setup-jest.ts
chore: setting jest angular preset configs
Added angular preset for jest and updated some deprecated properties.
> chore: setting jest angular preset configs

- projects/components/src/select/select.component.scss
- projects/components/src/table/controls/table-controls.component.ts
- projects/distributed-tracing/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
Fixes issue with table control multi select checkboxes not diffing correctly.
> fix: issues with checkbox diffing

- projects/observability/src/shared/dashboard/data/graphql/table/explore/explore-table-data-source.model.ts
- projects/observability/src/shared/graphql/request/builders/specification/explore/explore-specification-builder.ts
> refactor: fixing interval specification

- projects/observability/src/pages/apis/backend-detail/traces/backend-trace-list.dashboard.ts
Adding Destination column in backend trace (call) view.
NA
> chore: adds destination column in backend trace view

- projects/distributed-tracing/src/shared/dashboard/dashboard-wrapper/navigable-dashboard.component.ts
Updating data after clicking on a node in the topology or modifying an implicit filter.
Visual Testing.
> fix: updating page data after modify an implicit filter

- projects/components/src/navigation/navigation-list.component.scss
minor style changes for navbar
> fix(navbar): minor style changes

- projects/distributed-tracing/src/shared/graphql/request/builders/argument/graphql-argument-builder.test.ts
- projects/distributed-tracing/src/shared/graphql/request/builders/argument/graphql-argument-builder.ts
- projects/observability/src/shared/graphql/request/builders/argument/graphql-observability-argument-builder.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-builder.service.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/entities-graphql-query-handler.service.test.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/interactions/interactions-graphql-query-handler.service.test.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.test.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.ts
We deprecated the enum version of this and replaced with a string a little while back - making the change here in UI
Updated UT, manual verification
> refactor: switch to string entity type argument

- projects/components/src/table/table.component.scss
- projects/components/src/table/table.component.ts
Remove pointer on table unless the row is selectable (cells already apply a pointer style if clickable)
Visual
> chore: pointer only on selectable

- projects/assets-library/assets/styles/_font.scss
Adding new header font.
Note: This new font is similar to subtitle-1 but with a different default color. 
Not necessary.
> feat: adding new font

- Dockerfile
Update nginx to latest stable
Build and ran locally
> chore: update nginx

- projects/distributed-tracing/src/shared/components/span-detail/span-data.ts
refactor: marking startTime as optional
> refactor: marking startTime as optional

- projects/observability/src/shared/dashboard/data/graphql/waterfall/api-trace-waterfall-data-source.model.ts
> fix: log events attributes function

- projects/observability/src/pages/apis/api-detail/metrics/api-metrics.dashboard.ts
- projects/observability/src/pages/apis/backend-detail/metrics/backend-metrics.dashboard.ts
- projects/observability/src/pages/apis/service-detail/metrics/service-metrics.dashboard.ts
fix: updating label since chart shows selectable interval
> fix: updating label since chart shows selectable interval

- projects/components/src/combo-box/combo-box.component.ts
Removes the "Create" option when no search text is provided.
> feat: remove create option when empty searchString

- projects/components/src/time-picker/time-picker.component.scss
Minimum Time-picker changes in styles
Visual Testing
old:
new:
> fix: Adjusting styles

- projects/distributed-tracing/src/public-api.ts
> fix: export trace detail service

- projects/common/src/color/color.ts
> minor: add new color constant

- projects/components/src/combo-box/combo-box.component.scss
Minor style update for combo box content to align with mocks and make it prettier.
> fix: minor style update for combo box content

- projects/components/src/summay-card/summary-card.component.test.ts
- projects/components/src/summay-card/summary-card.component.ts
- projects/components/src/summay-card/summary-card.ts
separate indicator and header color inputs in summary card component
> feat: separate indicator and header color inputs in summary card component

- projects/components/src/summay-card/summary-card.component.scss
add styles for more colors in summary card
> fix: add styles for more colors in summary card

- projects/components/src/header/page/page-header.component.ts
- projects/components/src/tabs/navigable/navigable-tab.component.ts
support feature flagging tabs in page header
> feat: support feature flagging tabs in page header

- projects/components/src/checkbox/checkbox.component.scss
- projects/components/src/checkbox/checkbox.component.ts
- projects/components/src/radio/radio-group.component.scss
- Updating styles of checkbox disabled
- Adjusting background color in the checkbox (same as radio buttons)
Old: 
New:
> feat: adding styles to checkbox disabled

- projects/components/src/button/button.component.scss
- Adding PlainText Button style in small size. 
Visual Testing.
> feat: adding pending style

- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.scss
- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.ts
- projects/observability/src/shared/components/gauge-list/gauge-list.component.scss
- projects/observability/src/shared/dashboard/widgets/topology/topology-widget-renderer.component.scss
refactor: entity changes for api-dashboard
> refactor: entity changes for api-dashboard

- projects/assets-library/assets/icons/virtual-machine.svg
- projects/assets-library/src/icons/icon-library.module.ts
- projects/assets-library/src/icons/icon-type.ts
Add svg icon for Virtual Machine
> feat: add icon for virtual machine

- projects/components/src/header/application/application-header.component.ts
refactor: adding an option to hide time range in page header
> refactor: adding an option to hide time range in page header

- projects/assets-library/assets/styles/_interaction.scss
> style: update style for raised shadow hover

- projects/components/src/sequence/sequence-chart.component.scss
- projects/components/src/table/table.component.scss
- projects/observability/src/shared/components/card-list/card-list.component.scss
Replacing hover over and select in the following components:
- Table
- Sequence Chart
- Card list
Note: this change was suggested by @anandtiwary so he should review it.
Visual.
> feat: replacing components with hover over gray

- projects/assets-library/assets/images/error-page.svg
- projects/components/src/not-found/not-found.component.scss
- projects/components/src/not-found/not-found.component.ts
Changes for new NOT FOUND page.
No changes on the existing test cases 
Before
After
> fix: new design for not found page

- projects/observability/src/shared/components/topology/d3/layouts/custom-tree-layout.ts
> fix: fixing the child length

- package.json
- projects/observability/package.json
- projects/observability/src/shared/components/cartesian/chart.ts
- projects/observability/src/shared/components/cartesian/d3/axis/cartesian-axis.ts
Adding ticks count in Cartesian Chart Component
Visual Testing
> feat: Adding ticks count

- projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
- projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
This change adds timestamp formatting to endTime for Explorer table.
> Format explorer end time

- projects/components/src/button/button.component.scss
Cleaning unused button style
No testing
> feat: delete unused button style

- projects/components/src/confirmation/confirmation.service.ts
add support for size in confirmation modal service
Manual verification.
> feat: add support for size in confirmation modal service

- projects/components/src/table/controls/table-controls.component.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
> fix: some very minor clean up

- projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
Fix console error when table controls try to handle empty data sets.
> fix: table control filter dropdowns now handle empty result sets

- projects/observability/src/shared/dashboard/data/graphql/entity/entities-values-data-source.model.ts
This change will allow entity datasources to choose to includeInactive query param.
> Fix allow entity datasources include inactive

- projects/components/src/table/controls/table-controls-api.ts
- projects/components/src/table/controls/table-controls.component.test.ts
- projects/components/src/table/controls/table-controls.component.ts
- projects/observability/src/pages/apis/endpoints/endpoint-list.dashboard.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget-control-multi-select-option.model.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget-control-select-option.model.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget.module.ts
This change allows table dropdown controls to be configured for single or multi-select.
> Allow configurable select or multiselect table controls

- projects/components/src/table/table.component.scss
- projects/components/src/table/table.component.ts
Hides header bottom border when mode is Detail and style is List.
> feat: hide header divider line when in detail list mode

- projects/observability/src/shared/dashboard/data/graphql/entity/entities-values-data-source.model.ts
- projects/observability/src/shared/graphql/request/builders/selections/observability-specification-builder.ts
- projects/observability/src/shared/graphql/request/builders/specification/entity/entity-specification-builder.test.ts
- projects/observability/src/shared/graphql/request/builders/specification/entity/entity-specification-builder.ts
feat: add additional specification array to entity spec
> feat: add additional specification array to entity spec

- projects/components/src/public-api.ts
Import Filter URL Service
Not necessary
> feat: import filter url service

- projects/components/src/divider/divider.component.scss
> fix: make divider 1px high

- projects/observability/src/shared/dashboard/widgets/table/table-widget-base.model.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget-renderer.component.ts
- projects/observability/src/shared/dashboard/widgets/table/table-widget-view-toggle.model.ts
Adding loading config functionality to table view toggle widget
> feat: adding loading config functionality to table view toggle widget

- projects/observability/src/public-api.ts
- projects/observability/src/shared/graphql/model/schema/timerange/graphql-time-range.ts
- projects/observability/src/shared/utils/time-range.test.ts
- projects/observability/src/shared/utils/time-range.ts
util methods to manipulate graphqlTimeRange
UTs added.
> feat: util methods to manipulate graphqlTimeRange

- projects/components/src/table/controls/table-controls.component.scss
- projects/components/src/table/controls/table-controls.component.ts
Applied table filters will highlight blue.
> Table filters highlight applied

- projects/components/src/table/table.component.ts
support for custom row size for table
Tested locally.
> fix: support for custom row height for table

- projects/components/src/list-view/list-view.component.scss
- projects/components/src/multi-select/multi-select.component.ts
fix: minor style changes to list view and multi select
> fix: minor style changes to list view and multi select

- projects/components/src/input/input.component.ts
By this, we can set disabled state directly from form control for input component (which is recommended in reactive forms)
Manual testing done!!!
> feat: disabled state for input component reactive forms

- projects/components/src/combo-box/combo-box.component.scss
- projects/components/src/combo-box/combo-box.component.ts
- projects/components/src/form-field/form-field.component.scss
refactor: minor style change support for combo box
> refactor: minor style change support for combo box

- projects/common/src/time/time.test.ts
- projects/common/src/time/time.ts
Adding to ISOString function
Visual testing.
> feat: toISOString Time function

- projects/components/src/datetime-picker/datetime-picker.component.ts
- projects/components/src/form-field/form-field.component.ts
- projects/components/src/textarea/textarea.component.ts
- projects/components/src/time-picker/time-picker.component.scss
1. Datetime picker as form field
2. Text area as form field
3. Min width for time picker (style looks weird when value is null)
4. no error border when showBorder is false
Manual testing done!!
> feat: datetime picker as form field

- projects/components/src/header/page/page-header.component.scss
- projects/components/src/header/page/page-header.component.ts
Add an input to select between alignment options for page header content.
N/A. Only style changes. Manually verified.
> feat: support alignment customization for page header content

- projects/components/src/combo-box/combo-box.component.ts
feat: add option to configure create option label
> feat: add option to configure create option label

- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.ts
Able to define a color for entity icon
> feat: entity icon color

- projects/common/src/color/color.ts
> refactor: add blue 6

- projects/components/src/navigation/navigation-list.component.scss
Update the overflow styles for the navigation list component.
https://user-images.githubusercontent.com/29002760/149281894-538faaf8-4a4a-4e70-81df-faf5d86a7b61.mov
> style(navigation): update overflow styles

- projects/dashboards/src/widgets/container/container-widget-renderer.component.scss
refactor: updating style for container widget as per the mocks
> refactor: updating style for container widget as per the mocks

- projects/components/src/overlay/sheet/sheet-overlay.component.ts
refactor: remove tooltip from attached trigger
Tooltip can be added from content
> refactor: remove tooltip from attached trigger

- .github/workflows/build-and-test.yml
Update codecov as old loader is sunset
> ci: update codecov

- projects/assets-library/src/icons/icon-type.ts
- projects/components/src/button/button.component.scss
refactor: minor styling changes
> refactor: minor styling changes

- projects/common/src/color/color.ts
> style(ui): added new color

- src/app/application-frame/application-frame.component.ts
- src/app/shared/telemetry/user-telemetry-orchestration.service.ts
feat: adding user telemetry orchestration service
> feat: adding user telemetry orchestration service

- projects/components/src/filtering/filter/builder/filter-builder-lookup.service.ts
- projects/components/src/filtering/filter/builder/types/string-array-filter-builder.ts
- projects/components/src/table/header/table-header-cell-renderer.component.scss
refactor: adding string array filter and minor table fix
> refactor: adding string array filter and minor table fix

- projects/components/src/radio/radio-group.component.scss
- projects/components/src/radio/radio-group.component.ts
- projects/components/src/radio/radio-option.ts
Disabling each radio button option individually.
Visual testing.
> Radio button options disabled

- projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.scss
Fix text styling for string array cell renderer
N/A
> fix(style): string array cell renderer styling

- projects/components/src/radio/radio-group.component.ts
Disabling state from Radio Group
Locally tested
> feat: adding disabled state

- projects/components/src/overlay/sheet/sheet-overlay.component.ts
This reverts commit 90d7e62601029541350322e4013c000f7448b79d.
Revert sheet height fix
> Revert "fix(sheet overlay): fix height computation for sheet (#1532)"

- projects/components/src/navigation/nav-item/nav-item.component.scss
- projects/components/src/navigation/navigation-list.component.scss
- projects/components/src/navigation/navigation-list.component.ts
Added vertical scrollbar for entire nav list container for regular and dark styles.  Also reverted all nav item border radius to 4px for dark styles.
> Nav list vertical scrollbar

- projects/components/src/color-picker/color-picker.component.ts
Deselecting color on the second click on a selected color icon
Tested locally
> feat: Deselecting color on double click

- projects/common/src/utilities/formatters/string/highlight.pipe.ts
- projects/components/src/combo-box/combo-box.component.ts
> fix: undefined str in highlight pipe

- projects/components/src/filtering/filter/filter-attribute.ts
Add `category` as an optional field to facilitate grouping of filters.
> feat(filter): add category as optional field

- projects/components/src/multi-select/multi-select.component.test.ts
- projects/components/src/multi-select/multi-select.component.ts
- projects/components/src/select/select.component.ts
- projects/observability/src/shared/graphql/request/handlers/explore/explore-query.ts
> refactor: showing options < 5 if search text is present

- projects/common/src/time/time-range.service.test.ts
- projects/common/src/time/time-range.service.ts
> Handle zero case for time range query param

- projects/components/src/overlay/sheet/sheet-overlay.component.scss
- projects/components/src/overlay/sheet/sheet-overlay.component.ts
- projects/components/src/overlay/sheet/sheet.ts
Make default padding of the sheet component configurable.
> feat(sheet): make padding configurable

- projects/assets-library/assets/icons/alert-fill.svg
- projects/assets-library/src/icons/icon-library.module.ts
- projects/assets-library/src/icons/icon-type.ts
> feat(icon): add alert fill icon

- projects/components/src/number-input/number-input.component.ts
Adding Number Input Control Value Accessor
Locally tested
> feat: Adding Control Value Accessor on NumberInputComponent

- projects/components/src/table/cells/data-renderers/table-data-cell-renderer.component.scss
refactor: adding height to table cell
> refactor: adding height to table cell

- projects/observability/src/shared/components/utils/svg/svg-util.service.ts
fix: setting default value for dy
> fix: setting default value for dy

- projects/components/src/table/cells/data-renderers/table-data-cell-renderer.component.scss
Fixing Cell Renderer content
Local tested
> fix: cell renderer content

- projects/components/src/color-picker/color-picker.component.scss
- projects/components/src/color-picker/color-picker.component.ts
Disabling ColorPicker
Locally tested
> feat: Adding disable property to ColorPicker

- projects/components/src/filtering/filter/parser/types/in-filter-parser.ts
- projects/components/src/table/table.component.ts
fix: adding fix for boolean parser for in filter
> fix: adding fix for boolean parser for in filter

- projects/components/src/paginator/paginator.component.scss
- projects/components/src/paginator/paginator.component.ts
Add *Compact* mode for paginator:
- Wont show rows per page
- Reduced spacing
> feat(paginator): add compact view

- projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.test.ts
- projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts
When TR is changed, the interval in the UI is updated, but in the case where the TR change results in a new interval, the query itself is not. This change updates the query in that case.
Updated UTs, tested E2E
> fix: update explorer interval on tr change

- projects/components/src/table/data/table-cdk-data-source.ts
> fix: table pagination

- projects/components/src/info-icon/info-icon.component.test.ts
- projects/components/src/info-icon/info-icon.component.ts
- projects/components/src/info-icon/info-icon.module.ts
- projects/components/src/public-api.ts
- projects/components/src/tabs/content/tab-group.component.scss
- projects/components/src/tabs/content/tab-group.component.ts
- projects/components/src/tabs/content/tab.module.ts
- projects/components/src/tabs/content/tab/tab.component.ts
- projects/components/src/tabs/navigable/navigable-tab-group.component.scss
- projects/components/src/tabs/navigable/navigable-tab-group.component.ts
- projects/components/src/tabs/navigable/navigable-tab.component.ts
- projects/components/src/tabs/navigable/navigable-tab.module.ts
- Adding info-icon component
- Add info icon component to navigable and non-navigable tabs
Testing is done locally
> feat: info icon component

- projects/components/src/table/data/table-cdk-data-source.ts
- projects/components/src/table/data/table-data-source.ts
> feat: revert client side pagination

- projects/components/src/table/data/table-cdk-data-source.ts
- projects/components/src/table/data/table-data-source.ts
> feat: table client side pagination

- projects/assets-library/assets/icons/speedometer.svg
- projects/assets-library/src/icons/icon-library.module.ts
- projects/assets-library/src/icons/icon-type.ts
Add Speedometer icon
Locally tested
> AddSpeedometerIcon

- projects/components/src/header/page/page-header.component.ts
> Add input config for page header TR toggle

- projects/components/src/number-input/number-input.component.scss
- projects/components/src/number-input/number-input.component.ts
- projects/components/src/number-input/number-input.module.ts
Adding disabled style to input number component
Locally tested
> feat: adding disabled style to input number

- projects/components/src/overlay/overlay.ts
- projects/components/src/overlay/sheet/sheet-overlay.component.scss
- projects/components/src/overlay/sheet/sheet-overlay.component.ts
Sheet title as a template
Local testing is done,
> feat: sheet title as template

- projects/components/src/filtering/filter/filter-url.service.test.ts
- projects/components/src/filtering/filter/filter-url.service.ts
feat: build URL filters and group by nav query params
> feat: build url filters and group by nav query params

- projects/components/src/popover/popover-ref.ts
feat: adding hover observable and host element getter for popover
> feat: adding hover observable and host element getter for popover

- projects/observability/src/pages/explorer/explorer-service.ts
> feat(explorer service): export drilldown filter interface

- projects/components/src/navigation/navigation.config.ts
Reverts hypertrace/hypertrace-ui#1731
> Revert "feat: add type to nav item group"

- projects/components/src/multi-select/multi-select.component.scss
- projects/components/src/multi-select/multi-select.component.test.ts
- projects/components/src/multi-select/multi-select.component.ts
- projects/components/src/multi-select/multi-select.module.ts
- projects/components/src/x-more/x-more.component.scss
refactor: moving to xmore component and adding a fixed width tooltip
> refactor: moving to xmore component and adding a fixed width tooltip

- projects/common/src/public-api.ts
Export *Time Ago Pipe* to make it available for use in `ts` files.
> feat: export time ago pipe

- projects/observability/src/shared/components/span-detail/span-detail.component.ts
Visibility of **Attributes** tab can be modified via input.
> feat(span-detail): configure visibility of show attributes tab

- projects/components/src/list-view/list-view.component.scss
- projects/components/src/list-view/list-view.component.ts
Adding a new style for list view component -> `border-separated`
> feat: add border separated style to the list view

- projects/components/src/table/table.component.ts
> fix: table row height

- projects/common/src/navigation/navigation.service.ts
Added get root path url in navigation service.
Tested on the local
-  My changes generate no new warnings
> fix: added function to get root path url in navigation service

- projects/observability/src/shared/components/card-list/card-list.component.scss
- projects/observability/src/shared/components/card-list/card-list.component.ts
- projects/observability/src/shared/components/card-list/card-list.module.ts
- projects/observability/src/shared/components/card-list/container/card-container.component.ts
Add disabled style for card container in the card list component
> feat: add card disabled style

- projects/components/src/stepper/stepper.component.ts
Add a method that would enable consumer to navigate to a step programmatically.
> feat(stepper): add navigate to step method

- projects/observability/src/pages/apis/backends/backend-list.component.ts
- projects/observability/src/pages/apis/backends/backend-list.dashboard.ts
- projects/observability/src/public-api.ts
export dashboard config for backend list
> fix: export dashboard config for backend list

- projects/components/src/modal/modal-container.component.ts
- projects/components/src/modal/modal.ts
Support applying custom styles in modal container
Tested manually.
> fix(modal container): support for custom styles

- projects/components/src/notification/notification.component.scss
update notification bar position
> fix: update notification bar position

- projects/observability/src/public-api.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/topology-specification-builder.test.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/topology-specification-builder.ts
Add topology specification builder
> feat: add topology specification builder

- projects/observability/src/shared/graphql/model/metrics/metric-aggregation.test.ts
- projects/observability/src/shared/graphql/model/metrics/metric-aggregation.ts
- projects/observability/src/shared/graphql/model/schema/metric/graphql-metric-aggregation.ts
- projects/observability/src/shared/graphql/model/schema/metrics/graphql-metric-aggregation-type.ts
- projects/observability/src/shared/graphql/request/builders/specification/metric/metric-aggregation-converters.ts
Distinct array metric aggregation support
> feat: distinct array metric aggregation support

- projects/components/src/multi-select/multi-select.component.test.ts
- projects/components/src/multi-select/multi-select.component.ts
Make `Select All` configurable via the `showSelectAll` input. Enabled by default.
> feat(multi-select): add config for select all

- projects/observability/src/public-api.ts
- projects/observability/src/shared/components/topology/d3/d3-topology.ts
- projects/observability/src/shared/components/topology/topology.component.ts
- projects/observability/src/shared/components/topology/topology.ts
Added a custom way for having interaction handlers for nodes and edges, which currently supports click
> feat: topology interaction handlers

- projects/components/src/multi-select/multi-select.component.scss
- projects/components/src/multi-select/multi-select.component.test.ts
- projects/components/src/multi-select/multi-select.component.ts
feat: adding custom control template to multi select
> feat: adding custom control template to multi select

- projects/common/src/utilities/dom/dom-element-scroll-into-view.service.ts
Add support for `scrollIntoView` args.
> feat(scroll): add scroll into view args

- projects/components/src/select/select.component.ts
Add explicit change detection run for when disabled state is change via Forms API
> fix(select): add explicit change detection after disable state change

- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/topology-specification-builder.ts
Edge filters support for entities topology queries.
Manual testing is done.
> feat: adding edge filters support for topology query handler

- projects/common/src/constants/application-constants.ts
- projects/observability/src/shared/components/explore-query-editor/explore-query-editor.component.ts
- projects/observability/src/shared/components/explore-query-editor/explore-query-editor.module.ts
- src/app/shared/feature-resolver/feature-resolver.service.ts
Applying order by fields for all users in traces
Locally tested
> feat: showing Order by for all users

- projects/assets-library/assets/icons/dot.svg
- projects/assets-library/src/icons/icon-library.module.ts
- projects/assets-library/src/icons/icon-type.ts
- projects/components/src/select/select-option.component.ts
- projects/components/src/select/select.component.ts
- Add Dot icon
- Ability to provide icon size for select option
> Add new icon + size customization in select option

- projects/components/src/filtering/filter/builder/types/string-array-filter-builder.ts
Adding new supported operators to StringArray filters
Locally tested
> Adding new supported operators

- projects/components/src/navigation/navigation-list.component.scss
> refactor: adding minor style changes

- projects/common/src/utilities/formatters/date/date-formatter.ts
- Renamed `DateAndTime` mode to `DateWithYearAndTime`.
- Introduced new format `DateOnlyAndTime`
- Added JsDoc comments
> feat(date): add new date format

- projects/observability/src/shared/components/cartesian/chart.ts
- projects/observability/src/shared/components/cartesian/d3/axis/cartesian-axis.ts
Add support for custom label for axis ticks.
> feat(chart): add support for custom label in cartesian chart axis

- projects/components/src/modal/modal-container.component.ts
- projects/components/src/modal/modal.ts
Add support for providing more dimension options to modal:
- `minHeight`
- `maxHeight`
- `minWidth`
- `maxWidth`
> feat(modal): add support for min and max dimensions for modal

- projects/components/src/navigation/navigation-list.component.scss
- projects/dashboards/src/widgets/container/container-widget.module.ts
- projects/dashboards/src/widgets/container/layout/max-content/max-content-container-layout.model.ts
> feat: adding a max content layout model

- projects/components/src/input-pill-list/input-pill-list.component.ts
Make placeholder customizable
N/A
> fix: make placeholder an input on pill list

- projects/components/src/table/cells/data-renderers/duration/duration-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/enum/string-enum-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/numeric/numeric-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/relative-timestamp/relative-timestamp-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/text-with-copy/text-with-copy-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/text/text-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/time-ago/time-ago-table-cell-renderer.component.scss
- projects/components/src/table/cells/data-renderers/timestamp/timestamp-table-cell-renderer.component.scss
- projects/observability/src/shared/components/entity-renderer/entity-renderer.component.scss
- projects/observability/src/shared/components/table/data-cell/entity/entity-table-cell-renderer.component.scss
- projects/observability/src/shared/components/table/data-cell/exit-calls/exit-calls-table-cell-renderer.component.scss
- projects/observability/src/shared/components/table/data-cell/metric/metric-table-cell-renderer.component.scss
- projects/observability/src/shared/dashboard/widgets/waterfall/waterfall/span-name/span-name-table-cell-renderer.component.scss
Updating fonts in table cells.
Manually verified
> fix: switch to body-2 fonts for table cells

- projects/components/src/popover/service/popover-hover-trigger.service.ts
- projects/components/src/public-api.ts
- projects/components/src/tooltip/actionable/actionable-tooltip.directive.test.ts
- projects/components/src/tooltip/actionable/actionable-tooltip.directive.ts
- projects/components/src/tooltip/tooltip.directive.ts
- projects/components/src/tooltip/tooltip.module.ts
New Directive `htActionableTooltip` is created to handle all actionable tooltips.
> feat: make tooltips actionable in the ui

- projects/components/src/radio/radio-group.component.ts
- Removed assertion in template.
- Remove `(change)="$event.stopPropagation()"`  as the event doesn't contain the method.
> fix(radio-group): remove assertion and stop propogation

- projects/components/src/icon/icon-size.ts
- projects/components/src/icon/icon.component.scss
Add `micro` icon size
Manual testing is done
> feat: add micro icon size

- projects/components/src/paginator/paginator.component.test.ts
- projects/components/src/paginator/paginator.component.ts
- This reverts commit 1aac787bd0f31f0bd5e7096b6bed98583b057b73.
> Paginator visibllity

- projects/observability/src/shared/dashboard/data/graphql/table/entity/entity-table-data-source.model.ts
Added support for default sorting in entity table
> fix: add support for default sort in entity table

- projects/components/src/stepper/stepper.component.test.ts
- projects/components/src/stepper/stepper.component.ts
- projects/components/src/stepper/tab/stepper-tab.component.ts
Add `editable` input configuration.
> feat(stepper): support for editable input

- projects/components/src/table/table.component.scss
- projects/components/src/table/table.component.ts
Reverts https://github.com/hypertrace/hypertrace-ui/pull/2008
> revert: reverting changes made with PR#2008

- projects/components/src/notification/notification.component.ts
remove aria-live from notification container
N/A
> fix: remove aria-live from notification container

- .github/workflows/build-and-test.yml
Adding a node setup step in GHA workflow.
> fix: setup node in GHA install workflow

- .github/workflows/publish.yml
> fix: fix publish in GHA

- projects/dashboards/src/test/dashboard-verification.ts
mock FeatureResolver with a default in mockDashboardProvider
> fix: mock featureResolver in mockDashboardProvider

- projects/common/src/utilities/validators/form-validators.ts
> feat: update commaSeparatedEmail form validator to handle isNil

- projects/components/src/filtering/filter-bar/filter-chip/filter-chip.service.test.ts
- projects/components/src/filtering/filter/builder/types/string-map-filter-builder.ts
- projects/components/src/filtering/filter/filter-operators.ts
- projects/components/src/filtering/filter/parser/filter-parser-lookup.service.ts
- projects/components/src/filtering/filter/parser/types/contains-filter-parser.ts
- projects/observability/src/shared/dashboard/data/graphql/filter/graphql-key-value-filter.model.ts
- projects/observability/src/shared/graphql/model/schema/filter/graphql-filter.ts
- projects/observability/src/shared/services/filter-builder/graphql-filter-builder.service.ts
Add support for not contains key operator
> feat: add not contains key filter support

- projects/components/src/multi-select/multi-select.component.scss
> feat: add medium size css for multi select

- projects/components/src/public-api.ts
> feat(loader): export

- projects/components/src/table/columns/table-edit-columns-modal.component.scss
- projects/components/src/table/columns/table-edit-columns-modal.component.ts
- projects/components/src/table/table.module.ts
Adding drag and drop to re-ordering item list
Tested Locally
https://user-images.githubusercontent.com/79482271/231827415-43173df9-1bb3-498e-987a-8eb3f99e6ff5.mov
> Add drag and drop into edit columns modal

- projects/common/src/color/color.ts
> fix: added turquoise color

- projects/observability/src/shared/components/donut/donut-builder.service.ts
> fix: numeric formatter in donut builder

- projects/common/src/utilities/angular/pipes/index.ts
- projects/common/src/utilities/angular/pipes/is-empty/is-empty.pipe.module.ts
- projects/common/src/utilities/angular/pipes/is-empty/is-empty.pipe.ts
Angular pipe for lodash `isEmpty` method.
N/A
> feat: `isEmpty` pipe

- projects/components/src/button/button.component.scss
- projects/components/src/button/button.component.ts
- projects/components/src/link/link.component.ts
- projects/components/src/navigation/nav-item/nav-item.component.ts
- projects/components/src/navigation/navigation-list.component.ts
- projects/components/src/paginator/paginator.component.ts
- Add `aria-label` to links.
- Color contrast correction (AA) for `quaternary` button style.
> feat(accessibility): add aria labels

- projects/components/src/checkbox/checkbox.component.ts
> add aria label to ht-checkbox

- projects/components/src/toggle-switch/toggle-switch.component.ts
> feat: add default aria label to toggle switch

- projects/common/src/color/color.ts
> add orange-6 color

- projects/components/src/combo-box/combo-box.component.ts
- projects/components/src/filtering/filter-bar/filter-bar.component.scss
- projects/components/src/filtering/filter-bar/filter-bar.component.ts
- projects/components/src/filtering/filter-bar/filter-chip/filter-chip.component.ts
> fix: traces page accessibility

- projects/components/src/open-in-new-tab/open-in-new-tab.component.ts
- projects/components/src/viewer/json-viewer/json-viewer.component.scss
- projects/observability/src/shared/components/legend/legend.component.scss
- Chart legend color contrast fix.
- Open in a new tab component aria label added.
- JSON Viewer color contrast fix.
> fix(a11y): minor updates

- projects/components/src/button/button.component.scss
- projects/components/src/notification/notification.component.scss
- projects/components/src/notification/notification.component.test.ts
- projects/components/src/notification/notification.component.ts
- projects/components/src/notification/notification.module.ts
- projects/components/src/notification/notification.service.test.ts
- projects/components/src/notification/notification.service.ts
Update notification component style.
Add support for taking custom content template.
Updated UTs. Tested locally.
> feat: updates to notification component and service

- projects/components/src/download-file/download-file.component.ts
- projects/components/src/file-upload/file-upload.component.scss
Removing wrong padding, updating styles and adding ariaLabel
Locally tested.
> fix: Adding aria-label to Download button and updating styles

- projects/components/src/form-field/form-field.component.scss
Update optional color to support accessibility
Locally Tested
> fix: update optional color

- projects/observability/src/shared/components/explore-filter-link/explore-filter-link.component.ts
Adding aria label to explore filter link
Tested locally
> Adding aria label to explore filter link

- .eslintrc.json
- projects/components/src/checkbox/checkbox.component.scss
- projects/components/src/table/cells/expanded-detail/table-expanded-detail-row-cell-renderer.component.scss
- projects/components/src/table/header/table-header-cell-renderer.component.scss
- projects/components/src/table/header/table-header-cell-renderer.component.test.ts
- projects/components/src/table/header/table-header-cell-renderer.component.ts
- projects/components/src/table/table.component.scss
- projects/components/src/table/table.component.test.ts
- projects/components/src/table/table.component.ts
- projects/components/src/table/table.module.ts
1. Table Header Fixes
- Updating header background color
- Removed the state code
- Updating classes
2. Checkbox style fixes
- This will be a product-wide change
- Style updates for showing the indeterminate state correctly
- updated check box border styles
3. Table fixes
- Extracting out state columns to the table component instead of having them as cell renderers. And Similar to the header
- Making state columns sticky and adding border-right
- Removing selections on pagination
- Updating borders for the detail content and cells
Manual testing is done.
> fix: table related issues

- projects/components/src/notification/notification.component.scss
Update margin top
Tested locally.
> fix: update toast notif container top margin

- projects/components/src/load-async/loader/loader.component.ts
Adding Alt to Loader
Not necessary
> feat: adding alt to Loader

- projects/dashboards/src/widgets/text/text-widget-renderer.component.scss
Fix contrast accessibility
Not necessary
> fix: text widget renderer accessibility

- projects/common/src/color/color-palette.ts
- projects/common/src/color/color.ts
define getContrastColor method as public util method
> feat: define getContrastColor method as public util

- projects/common/src/utilities/formatters/time/display-time-ago.pipe.ts
customizable suffix for time ago pipe
> fix: customizable suffix for time ago pipe

- projects/components/src/table/table.component.test.ts
- projects/components/src/table/table.component.ts
Reverts hypertrace/hypertrace-ui#2227
> Revert "feat: run change detection after updating the visible columns"

- projects/components/src/collapsible-sidebar/collapsible-sidebar.component.test.ts
- projects/components/src/form-field/form-field.component.test.ts
- projects/components/src/toggle-switch/toggle-switch.component.test.ts
Improving tests
Locally tested
> feat: Improving tests duration

- projects/components/src/table/table.component.ts
Reverts hypertrace/hypertrace-ui#2235
> Revert "fix: table auto layout fix"

- projects/components/src/notification/notification.service.ts
- Config override for `info` toast.
- Add Manual `close` method.
> feat(notification): add config override and manual close

- projects/components/src/table/controls/table-controls-api.ts
- projects/components/src/table/controls/table-controls.component.ts
This fix is when the select control is not showing a value after selecting an option, also adding the possibility to remove a selection.
Tested locally
> fix: table control select

- projects/common/src/feature/state/feature-state.resolver.ts
Extend FF value type to include string array type.
> fix: add support for string array in FF value

- projects/components/src/download-file/service/file-download.service.ts
convert png downloader to generic blob downloader
> fix: convert png downloader to generic blob downloader

- projects/components/src/feature-check/feature-config-check.module.ts
- projects/components/src/feature-check/is-feature-state-enabled.pipe.test.ts
- projects/components/src/feature-check/is-feature-state-enabled.pipe.ts
A pipe to check if the feature state is enabled.
> feat: new isFeatureEnabled pipe

- projects/observability/src/shared/dashboard/widgets/trace-detail/data/trace-detail-data-source.model.ts
Adding attributes to TraceDetailData
Locally tested
> feat: adding attributes to TraceDetailData

- projects/common/src/time/time-duration.ts
Supporting Max Unit into Time duration
Locally tested
> feat: Support Max unit into time duration

- projects/common/src/navigation/navigation.service.ts
> feat(nav): add new method

- projects/components/src/filtering/filter-button-wrapper/filter-button-wrapper.component.ts
- projects/components/src/filtering/filter-button-wrapper/filter-button-wrapper.module.ts
- projects/components/src/public-api.ts
- projects/observability/src/pages/explorer/explorer.component.ts
- projects/observability/src/shared/components/cartesian/cartesian-chart.module.ts
- projects/observability/src/shared/components/cartesian/chart.ts
- projects/observability/src/shared/components/cartesian/d3/legend/cartesian-legend.ts
- projects/observability/src/shared/components/explore-query-editor/explore-visualization-builder.ts
- projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.ts
Adding filter option to legends on traces
Locally tested
> feat: adding filters to legends

- projects/observability/src/pages/explorer/explorer.component.ts
- projects/observability/src/pages/explorer/explorer.module.ts
Adding selector to Explore
Not Necessary
> feat: adding explore selector

- projects/components/src/input-pill-list/input-pill-list.component.test.ts
- projects/components/src/input-pill-list/input-pill-list.component.ts
- projects/components/src/input/input.component.scss
- projects/components/src/input/input.component.test.ts
- projects/components/src/input/input.component.ts
- projects/components/src/menu-dropdown/menu-item/menu-item.component.ts
> feat: remove inputFocus Output from Input component

- projects/components/src/splitter/splitter.component.scss
- projects/components/src/splitter/splitter.component.ts
> style: fix splitter styling

- projects/assets-library/assets/styles/_font.scss
- projects/graphql-client/src/graphql-execution-error.ts
- projects/graphql-client/src/graphql-request-error.ts
- projects/graphql-client/src/graphql-request.api.ts
- projects/graphql-client/src/graphql-request.service.ts
- projects/graphql-client/src/public-api.ts
> feat: expose error handling in graphql request service

- projects/components/src/table/table.component.test.ts
- projects/components/src/table/table.component.ts
Do not emit state column in columnConfigsChange
> fix: do not emit state column in columnConfigsChange

- projects/components/src/filtering/filter-button-wrapper/filter-button-wrapper.component.ts
- projects/components/src/filtering/filter-button/filter-button.component.ts
- projects/components/src/filtering/filter/builder/types/abstract-filter-builder.ts
- projects/components/src/public-api.ts
- projects/observability/src/shared/components/cartesian/chart.ts
- projects/observability/src/shared/components/cartesian/d3/legend/cartesian-legend.ts
- projects/observability/src/shared/dashboard/data/graphql/explore/explore-cartesian-data-source.model.ts
Adding Filters for Supported Subpath Operators
Locally Tested
> feat: Adding filters for supported subpath operators

- projects/components/src/splitter/splitter.component.scss
> fix: disallow splitter overflow

- projects/observability/src/shared/components/span-detail/call/headers/span-detail-call-headers.component.ts
- projects/observability/src/shared/components/span-detail/request/span-request-detail.component.ts
- projects/observability/src/shared/components/span-detail/response/span-response-detail.component.ts
Fixing issue added in https://github.com/hypertrace/hypertrace-ui/pull/2414
Locally tested
> fix: renaming variables in span details

- projects/observability/src/pages/explorer/explorer-dashboard-builder.test.ts
- projects/observability/src/pages/explorer/explorer-dashboard-builder.ts
- projects/observability/src/shared/services/metadata/metadata.service.ts
Adding Attribute's columns to Traces
Locally Tested
> feat: adding attribute columns to traces

- projects/common/src/time/time-range.service.ts
refactor: emit a new time range object on refresh
> refactor: emit a new time range object on refresh

- projects/common/src/public-api.ts
- projects/common/src/utilities/angular/pipes/index.ts
- projects/common/src/utilities/validators/index.ts
- projects/components/src/public-api.ts
- projects/components/src/stepper/index.ts
> Remove barrel files 

- projects/observability/src/public-api.ts
> feat: expose MetricTimeseriesSpecificationModel

- projects/components/src/table/cells/csv-generators/table-cell-string-enum-csv-generator.test.ts
- projects/components/src/table/cells/csv-generators/table-cell-string-enum-csv-generator.ts
- projects/components/src/table/table.module.ts
csv generator for string enum type
> feat: csv generator for string enum type

- projects/components/src/filtering/filter-button/filter-button.component.ts
Adding a null filter by default
Locally Tested
> feat: Adding Simplified Filters (null)

- projects/components/src/select/select-option.ts
- projects/components/src/select/select.component.ts
Show tooltip in select if provided.
> feat(select): show tooltip

- projects/observability/src/shared/components/explore-query-editor/group-by/explore-query-group-by-editor.component.scss
- projects/observability/src/shared/components/explore-query-editor/group-by/explore-query-group-by-editor.component.ts
Fixing group by key title:
old:
new:
Locally Tested
> fix: fixing group by key title

- projects/components/src/input/input.component.scss
> feat: update styling for input placeholder

- projects/common/src/utilities/lang/lang-utils.ts
Add null to undefined util for cleaning up server responses
> refactor: add null to undefined util

- package-lock.json
- package.json
Reverts hypertrace/hypertrace-ui#2511
> Revert "chore:(deps-dev): bump @angular-eslint/eslint-plugin-template from 15.2.1 to 17.0.1"

- projects/components/src/file-upload/file-upload.component.test.ts
- projects/components/src/file-upload/file-upload.component.ts
> feat(file-upload): support custom file requirements

- projects/components/src/splitter/splitter.component.scss
- projects/components/src/splitter/splitter.component.ts
> feat: add disabled mode to splitter

- projects/observability/src/shared/dashboard/data/graphql/topology/topology-data-source.model.test.ts
- projects/observability/src/shared/dashboard/data/graphql/topology/topology-data-source.model.ts
- projects/observability/src/shared/graphql/request/handlers/entities/query/topology/entity-topology-graphql-query-handler.service.ts
Adds support for entity scoped edge filters to topology data source and query handler
> fix: adding edge entity filters support

- projects/observability/src/pages/explorer/explorer.component.test.ts
- projects/observability/src/shared/dashboard/data/graphql/table/spans/spans-table-data-source.model.ts
remove prefetching on spans table
> fix: remove prefetching on spans table

- projects/observability/src/shared/graphql/model/metrics/metric-aggregation.test.ts
- projects/observability/src/shared/graphql/model/metrics/metric-aggregation.ts
- projects/observability/src/shared/services/metadata/metadata.service.test.ts
> feat: metric aggregation type type guard

- projects/components/src/stepper/stepper.component.scss
Stepper header height quick fix.
> style(stepper): header height fix

- projects/components/src/public-api.ts
- projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.test.ts
- projects/components/src/table/cells/data-renderers/string-array/string-array-table-cell-renderer.component.ts
- projects/components/src/table/cells/data-renderers/string-array/types.ts
export string array table cell common types
> chore: export string array table cell common types
